[feature] Migrate door prefab + anims
InShine-Studios/Horror-3D pull request #109
Opened 2022-01-18 14:05 UTC by rafiftaris

### Main changes
- add door prefab
- add door anim (open/close)

### Tasks List
- [close #31 ]
- [close #32 ]

### Attachments

https://user-images.githubusercontent.com/51603162/149952160-a2db7fce-c349-46e6-b78d-c916d916c484.mp4

2022-01-19 04:17 UTC, naufalhilmi12345 requested changes
player to close to close the door so player move a little when close the door

2022-01-19 23:56 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-20 13:45 UTC, raihansyahdean requested changes
- Add interactable icon for doors (use 3D Exclamation Mark prefab for now)
- Move "VoxelObjs" to "Arts" folder

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Tests/PlayerTest.cs
> +        float moveDuration = GetMovementDurationTowards(GameObject.Find("LightSwitch").transform);
LightSwitch object is searched more than once. Better save this object to a variable to do less computation

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Tests/PlayerTest.cs
> +        inputTestFixture.Press(KeyboardMouseTestFixture.RegisteredInput.Interact);
When turning the lights on there are both press and release calls. But when turning the lights off only press is called. Should there also be a Release call for consistency?

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Controller/DoorController.cs
> +    private bool isOpen = false;
Rename to: _isOpen

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Controller/DoorController.cs
> +    private const string animParam = "isOpen";
Rename to : _animParam

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Controller/DoorController.cs
> +        Debug.Log("[INTERACTABLE] Door interacted");
Comment this line

2022-01-20 13:45 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Controller/DoorController.cs
> +        isOpen = !_doorAnim.GetBool(animParam);
Better use isOpen = !isOpen for simplicity

2022-01-21 04:58 UTC, raihansyahdean approved these changes

2022-01-21 04:58 UTC, merged