[feature] Implement ankh item and testing for ankh
InShine-Studios/Horror-3D pull request #132
Opened 2022-01-24 04:17 UTC by naufalhilmi12345

### Main changes

- implement ankh item and testing for ankh

### Tasks List

- [close #95]

### Attachments

https://user-images.githubusercontent.com/44135006/150721136-3b090ab8-9cd5-410c-a4b6-66b4a7bc9c13.mp4

2022-01-24 12:21 UTC, rafiftaris requested changes

2022-01-24 12:21 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/DummyAnkh.cs
> +        _inAstral = !_inAstral;
put this at the first line of function for better readability

2022-01-24 12:21 UTC, rafiftaris commented on Assets/Astralization/Tests/Interactable Tests/InteractableTest.cs
> +    private GameObject astral;
renaming according to convention will be done in my refactor, for now this is passed

2022-01-24 12:21 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/DummyAnkh.cs
> +public class DummyAnkh : Item
rename all DummyAnkh to Ankh because item with Dummy prefix will not be implemented for production

2022-01-24 12:21 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/DummyAnkh.cs
> +/*
fix class docs

2022-01-24 12:21 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/DummyAnkh.cs
> +        bool bConverted = ColorUtility.TryParseHtmlString("#5F466A", out _col);
extract fog configuration to utils

2022-01-24 12:23 UTC, rafiftaris requested changes

2022-01-24 12:23 UTC, rafiftaris commented on Assets/Astralization/Tests/Interactable Tests/InteractableTest.cs
> +            else if (gameObject.name == "VOL_Global_AstralWorld_1")
put this on test case instead

2022-01-25 12:07 UTC, rafiftaris approved these changes
mantapp!! 👍👍

2022-01-25 12:08 UTC, RaiRiz approved these changes
gudd

2022-01-25 13:25 UTC, raihansyahdean requested changes

2022-01-25 13:25 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +        Color _col = Utils.ColorParser.GetColor("#5F466A");
Local variables dont need to use _, rename to col.
Also put this in the if statement as it is only used in the if statement

2022-01-25 13:25 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Utils/ColorParser.cs
> +            else return Color.black;
I dont think that this line is needed. Parser should only parse the color, if the parsing failed then raise an error instead

2022-01-25 13:25 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +        _astralWorld.SetActive(_inAstral);
Add TODO: Call PlayAudio for Ankh

2022-01-25 13:25 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +        _astralWorld.SetActive(_inAstral);
and also TODO: Implement transition animation

2022-01-27 13:06 UTC, raihansyahdean approved these changes
Nice

2022-01-27 13:07 UTC, merged