[feature] Created Astral Meter Logic + Tests
InShine-Studios/Horror-3D pull request #133
Opened 2022-01-25 12:18 UTC by VadimBhirawa

### Main changes
Created Astral Meter Logic Script. Also created Tests for the Script.

### Tasks List
- [close #130]

2022-01-25 13:33 UTC, rafiftaris requested changes

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    private float sightAmount = 1.0f;
rename to _sightAmount

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    public bool isOnRealWorld = true;
set to private, rename to _isOnRealWorld

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    public bool isOnSight = false;
set to private, rename to _isOnSight

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    private void Start()
delete this

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    public bool World()
rename to IsOnRealWorld

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    public bool OnSight()
rename to IsOnSight

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    public void ChangeSight()
rename to ChangeSightState

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Scripts/Party/AstralMeterLogic.cs
> +    void Update()
put Update below Start

2022-01-25 13:33 UTC, rafiftaris commented on Assets/Astralization/Tests/Interactable Tests/AstralTest.cs
> +}
add new line

2022-01-26 09:02 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-26 14:12 UTC, rafiftaris approved these changes
TIL jangan pecicilan pas nunggu test

2022-01-26 14:13 UTC, merged