[refactor] tests
InShine-Studios/Horror-3D pull request #134
Opened 2022-01-25 12:39 UTC by rafiftaris

### Main changes
- Refactor test cases into spesific context with modifiable scene

### Tasks List
- [close #126 ]

### Attachments
![image](https://user-images.githubusercontent.com/51603162/150978387-15b90e27-0d8b-41aa-b804-cd3457f7ecfc.png)

2022-01-25 13:46 UTC, raihansyahdean requested changes

2022-01-25 13:46 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +                _activeIdx = -1;
remove this, index should stay at the discarded index

2022-01-28 23:36 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-30 15:43 UTC, raihansyahdean approved these changes
Very nice tests

2022-01-30 15:46 UTC, merged