Dean/refactor/observer patterns
InShine-Studios/Horror-3D pull request #142
Opened 2022-01-28 14:04 UTC by raihansyahdean

### Main changes
- Rafactor audio pattern
- Overworld Item class
- Volume class
- Audio manager class (not observer, but find child so no longer using manual assignment)

### Tasks List
- [close #120 ]
- [close #139 ]

### Attachments
![image](https://user-images.githubusercontent.com/42737788/151560277-df58b8a9-b44d-4396-a699-cd1943d9636d.png)
![image](https://user-images.githubusercontent.com/42737788/151560264-25436258-e35d-4c47-8fc4-8fe480c1c596.png)

### New Packages
N/A

### Resources 
N/A

2022-01-28 14:11 UTC, VadimBhirawa approved these changes
Looks good!

2022-01-28 23:36 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-29 01:42 UTC, RaiRiz approved these changes
LGTM!

2022-01-29 06:47 UTC, rafiftaris requested changes

2022-01-29 06:47 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Interactable.cs
> +    protected AudioManager _audioManager;
protected field use PascalCase

2022-01-29 06:47 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +            int indexShift = (int) (scrollValue / (_scrollStep * ScrollSensitivity));
use GetScrollStep

2022-01-29 14:08 UTC, rafiftaris requested changes

2022-01-29 14:08 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +            int indexShift = (int) (scrollValue / (GetScrollStep()));
GetScrollStep gausah dikurungin

2022-01-29 14:12 UTC, rafiftaris approved these changes
mantap dah

2022-01-29 14:13 UTC, merged