[feature] Adding icon for item, closest, and animimation to switch
InShine-Studios/Horror-3D pull request #158
Opened 2022-01-30 14:59 UTC by naufalhilmi12345

### Main changes

- Adding icon for item
- Adding animation to light switch
- Closest item icon appear

### Tasks List

- [close #124]
- [close #125]
- [close #94]

### Attachments

- Closest icon

https://user-images.githubusercontent.com/44135006/151702068-555d560b-ed4c-451c-803d-33b13cdc978e.mp4

- Light Switch Animation

https://user-images.githubusercontent.com/44135006/151702088-83ea2021-e2b2-44b4-b608-a7e8f9e55cd4.mp4

- Interactable Icon for Item

https://user-images.githubusercontent.com/44135006/151702110-2e01ac43-8f9f-40db-b57b-a2535732de4b.mp4

2022-01-30 16:51 UTC, JahnsMichael commented on Assets/Astralization/Scripts/Player/Detectors/ObjectDetector.cs
> +    //bikin method baru
is this an important comment? if yes, I think it can be more descriptive for other developers that don't follow the progress from the start. if not, maybe it can be removed.

2022-01-30 16:53 UTC, JahnsMichael approved these changes
functional-wise LGTM and the code are quite readable for me, maybe the other reviewers can review the code in more detail. Good job bruh!

2022-01-31 03:16 UTC, rafiftaris requested changes
don't forget to test and add closest icon flow to feature docs

2022-01-31 03:16 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/ObjectDetector.cs
> +    private void test()
rename this function

2022-01-31 03:16 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/ObjectDetector.cs
> +    //bikin method baru
kalo beneran to do, kasih TODO di awal comment

2022-01-31 03:16 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerMovement.cs
> +        if (_useForceGrounding) ForceGrounding();
remove space between if and its condition

2022-01-31 03:16 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerMovement.cs
> +        if (_moveDirection.magnitude == 0) return false;
just return the if condition

2022-02-01 13:45 UTC, rafiftaris approved these changes
mantapp +500k changes

2022-02-01 13:55 UTC, rafiftaris requested changes
gajadi approve soalnya test listdan feature docs belom diupdate hehe

2022-02-02 06:26 UTC, merged