[feature] Created Game Manager Script + Tests
InShine-Studios/Horror-3D pull request #159
Opened 2022-01-31 07:19 UTC by VadimBhirawa

### Main changes
Created Game Manager Script to keep track of world state (Astral World or Real World), and keep track of Astral Meter accumulation.

### Tasks List
- [close #135 ]

2022-01-31 07:45 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +        //else RenderSettings.fogColor = Color.black;
if the system is work, maybe delete this comment

2022-01-31 07:46 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +    //private bool _inAstral = false; //TODO: Refactor this to GM
if the system is work, maybe delete this comment

2022-01-31 07:47 UTC, naufalhilmi12345 requested changes
i think the comment section code can be deleted

2022-01-31 09:09 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-31 11:33 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-01-31 13:33 UTC, raihansyahdean requested changes
I dont see any script to toggle the VolumeReal yet. I think you havent implement it fully.

2022-01-31 13:33 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/Ankh.cs
> +    public static event Action ChangeWorldGM; //TODO: Refactor this to GM
comment is no longer need, that action is already for GM

2022-01-31 13:33 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    private void OnEnable()
put enable disable before setter getter, and make it in a region as well

2022-01-31 13:33 UTC, raihansyahdean commented on Assets/Astralization/Scripts/States/AstralMeterLogic.cs
> +    public float GetAstralMeter()
put setter getter after enable disable and make it in a region

2022-02-01 01:18 UTC, rafiftaris requested changes
Assets/Astralization/Scripts/States/AstralMeterLogic.cs

- Rename Update() with another name, so the built-in Update() won't be overriden
<img width="480" alt="Screen Shot 2022-02-01 at 08 56 41" src="https://user-images.githubusercontent.com/51603162/151897321-384061bd-d737-4a90-9d69-c08b28a5a9c8.png">

2022-02-01 01:18 UTC, rafiftaris commented on Assets/Astralization/Tests/StateTest/AstralWorldEntryTest.cs
> +        inputTestFixture.Press(KeyboardMouseTestFixture.RegisteredInput.MoveLeft);
use yield return SimulateInput(), for reference see TestBase

2022-02-01 01:18 UTC, rafiftaris commented on Assets/Astralization/Tests/StateTest/AstralWorldEntryTest.cs
> +        inputTestFixture.Press(KeyboardMouseTestFixture.RegisteredInput.PickItem);
use yield return SimulateInput(), for reference see TestBase

2022-02-01 01:18 UTC, rafiftaris commented on Assets/Astralization/Tests/StateTest/AstralWorldEntryTest.cs
> +        inputTestFixture.Press(KeyboardMouseTestFixture.RegisteredInput.UseItem);
use yield return SimulateInput(), for reference see TestBase

2022-02-01 12:17 UTC, rafiftaris approved these changes

2022-02-01 14:56 UTC, raihansyahdean approved these changes
Finally, good job Vadim!!!

2022-02-01 14:58 UTC, merged