[feature] Adjust NPC Dialog Box and add Temporary Dialogue Text
InShine-Studios/Horror-3D pull request #167
Opened 2022-02-04 12:41 UTC by VadimBhirawa

### Main changes
Adjusted NPC Dialogue Box to be able to press enter to see the next line.

### Tasks List
- [close #131 ]

### Attachments
![Adjust Dialogue Box](https://user-images.githubusercontent.com/23608044/152530566-34bb3af8-21dd-4dad-bd4b-0cfbdf65acd1.gif)

2022-02-06 04:57 UTC, rafiftaris requested changes
- [BUG] when interact with npc for the 2nd time, dialogue is not resetted
- Add dialogue to feature docs, put it in HUD subsection
- Add NPC to feature docs, put it in Features section

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueInvoker.cs
> +public class DialogueInvoker : MonoBehaviour
add class docs

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +    public static event Action<bool> DialogueEvent;
event name is too general, rename this to FinishDialogue

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueInvoker.cs
> +    public static event Action DialogueInvoke;
event name is too general, rename this to StartDialogue

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +public class DialogueManager : MonoBehaviour, IDialogueManager
add class docs

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +    void StartDialogue()
this function is not called when the dialogue is starting, rename this to SetUpDialogue

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
> +        GameObject player = GameObject.Find("Party/Iris");
remove unused variables

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
> +
assert if the dialogue is updated

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
> +        /*yield return new WaitForSeconds(0.3f);
delete this

2022-02-06 04:57 UTC, rafiftaris commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
> +        yield return SimulateInput(KeyboardMouseTestFixture.RegisteredInput.NextDialogueEnter);
change this to left click

2022-02-07 03:29 UTC, rafiftaris approved these changes
cool! 🔥

2022-02-07 08:29 UTC, raihansyahdean requested changes
Integrate ShowDialogueBox with Next function

2022-02-07 08:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Controller/NpcController.cs
> +        //Debug.Log("OnInteraction: " + _isInteracted);
delete this debug, double with the one below

2022-02-07 08:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +            //Debug.Log("isInteractWithNpc: " + isInteractWithNpc);
remove this

2022-02-07 08:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +    public float TextSpeed;
make private, add [SerializeField]

2022-02-07 08:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +    private InputAction _next;
unused both variables, remove

2022-02-08 12:04 UTC, raihansyahdean approved these changes
Excellent!

2022-02-08 12:05 UTC, merged