[feature] roaming ghost
InShine-Studios/Horror-3D pull request #169
Opened 2022-02-07 02:23 UTC by rafiftaris

### Main changes
- Implemented StageController to store room coordinates
- Implemented ghost roaming by GhostMovement script and NavMeshAgent
- Implemented randomizer at Utils
- Implemented DraggablePointDrawer for scene editor (code is functioning but cluttered and too heavy to run, will refactor in separate issue )

### Tasks List
- [close #97 ]

### Attachments
https://user-images.githubusercontent.com/51603162/152714866-25057256-4dab-41d8-a66a-a18b18e94d7a.mov

2022-02-08 12:17 UTC, raihansyahdean requested changes
Excellent, just minor add region and documentation for TC and feature please.

2022-02-08 12:17 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Stage/StageController.cs
> +    public static List<string> GetRoomNames()
create setter getter region for all three functions

2022-02-08 12:19 UTC, naufalhilmi12345 approved these changes
LGTM!

2022-02-09 05:43 UTC, raihansyahdean approved these changes
Excellent!

2022-02-09 05:43 UTC, merged