[feature] EvidenceItem and Thermometer
InShine-Studios/Horror-3D pull request #170
Opened 2022-02-07 07:56 UTC by JahnsMichael

### Main changes

- add EvidenceItem base class
- add new Ghost Interaction Simulation Input Action
- add Thermometer temporary implementation

### Tasks List

- [close #145]
- [close #146]

### Attachments

https://user-images.githubusercontent.com/60375650/152746293-4f34c0c2-09e1-4fb5-b55f-9b853c9a6dda.mp4

Implemented State Transition
- Use --> Active (Yellow)
- When Active then Interacted by Ghost --> Evidence A (Blue)
- When Evidence A then Interacted by Ghost --> Evidence B (Red) (temporary/dummy behavior)
- Discard --> Inactive (Orange)
- When inactive then Interacted by Ghost --> Nothing

### New Packages

### Resources

2022-02-10 01:02 UTC, naufalhilmi12345 requested changes
Changing adding newline at EvidenceItem.cs

2022-02-10 06:26 UTC, JahnsMichael commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/EvidenceItem.cs
> +}
done

2022-02-10 06:47 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-02-11 07:44 UTC, rafiftaris requested changes
dont forget the feature docs and add testcases to TC list 😉

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/Thermometer.cs
> +        switch (this.state)
can be refactored: make Dictionary<EvidenceItemState, Material> and use the dictionary to set state material

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +    public bool GetDiscardWhenUsed()
rename to IsDiscardedWhenUsed. kalo returnnya boolean, lebih baik pake prefix Is/Are

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +                // Debug.Log("[INVENTORY] Discard " + _activeItem.name);
refactor: extract line 141-155 to another function and call that function

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +        Assert.AreEqual("MAT_Thermometer_Active (Instance)", stateMaterial.name);
assert the item state

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +        Assert.AreEqual("MAT_Thermometer_Base (Instance)", stateMaterial.name);
assert the item state

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +    public IEnumerator EvidenceItem_NotActivatedWhenUsed()
rename to EvidenceItem_NotActivatedWhenDiscarded

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +        Assert.AreEqual("MAT_Thermometer_Base (Instance)", stateMaterial.name);
assert the item state

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +        Assert.AreEqual("MAT_Thermometer_Positive (Instance)", stateMaterial.name);
assert the item state

2022-02-11 07:44 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/EvidenceItemTest.cs
> +        Assert.AreEqual("MAT_Thermometer_Negative (Instance)", stateMaterial.name);
assert the item state

2022-02-11 10:40 UTC, JahnsMichael commented
> dont forget the feature docs and add testcases to TC list wink

done

2022-02-12 09:06 UTC, rafiftaris approved these changes

2022-02-12 10:28 UTC, raihansyahdean requested changes

2022-02-12 11:58 UTC, JahnsMichael commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +    private void _DiscardItem()
done

2022-02-12 12:14 UTC, raihansyahdean approved these changes
Nice

2022-02-12 12:14 UTC, merged