[feature] Integrate Ink Dialogue Tools
InShine-Studios/Horror-3D pull request #188
Opened 2022-02-12 09:44 UTC by uciii

### Main changes
Integrate Ink to provide JSON to our dialogue flow

### Tasks List
- [close #177]

### Attachments
1. Ink folder (consist JSON file)
<img width="274" alt="image" src="https://user-images.githubusercontent.com/71260420/153706011-1f27cc39-e754-4d6b-b40b-fd2fe7b8858c.png">

2. Edit json in inky tools
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71260420/153706111-34bb63fb-a063-4d5d-9c91-9757b8be2c75.png">

3. Dialogue Box prefab > DialogueManager.cs > variable Dialogue Json should refer to Ink Dialogue.json
<img width="469" alt="image" src="https://user-images.githubusercontent.com/71260420/153706069-a6188380-1e9a-4f6c-976e-65dac7631584.png">

4. Result
<img width="769" alt="image" src="https://user-images.githubusercontent.com/71260420/153706133-6945d422-250d-4041-bdec-e415b50f79a7.png">

### New Packages
- [Ink Unity Integration](https://assetstore.unity.com/packages/tools/integration/ink-unity-integration-60055)
- Extra : [Inky tools](https://www.inklestudios.com/ink) (Ink editor)

2022-02-12 10:19 UTC, raihansyahdean requested changes
Move resource files to Astralization/Resources/Dialogue/DummyText.json etc.

2022-02-12 10:19 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/Ink/InkScript.cs
> +using Ink.Runtime;
remove this class

2022-02-12 10:19 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
> +    private TextAsset _dialogueJson;
make setter for _dialogueJson

2022-02-12 11:06 UTC, VadimBhirawa approved these changes
LGTM

2022-02-13 05:07 UTC, rafiftaris requested changes
perlu docs?

2022-02-13 05:07 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/DialogueManager.cs
>      bool GetDialogBox();
error CS0535: 'DialogueManager' does not implement interface member 'IDialogueManager.GetDialogBox()'

Rename this

2022-02-13 12:13 UTC, rafiftaris approved these changes

2022-02-13 12:23 UTC, merged