Exorcism Item + Channeling + HUD
InShine-Studios/Horror-3D pull request #190
Opened 2022-02-13 06:47 UTC by VadimBhirawa

### Main changes
Finished implementing exorcism channeling. Includes:
- Exorcism Item
- Channeling
- Player Action Map changed during channeling so player can't move but can still cancel channeling
- Exorcism bar on HUD to show channeling progress

### Tasks List
- [close #155 ]
- [close #156 ]

2022-02-13 13:00 UTC, rafiftaris requested changes

2022-02-13 13:00 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +    public abstract void ButtonReleased();
- overriding abstract with blank function is bad, move this abstract to more suitable class (ExorcismItem)
- rename function to StopUse

2022-02-13 15:45 UTC, rafiftaris requested changes

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    private float _minHold = 0f;
variable name doesn't represent its meaning. rename it to _sliderMinValue

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    private ExorcismBar _exorcismBar;
use HUD manager

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    #region Update - Awake
rename region

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    public float GetAccTime()
dont abbreviate function name

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    public bool GetUsed()
rename to IsUsed

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    #region Getter
rename region (see another script)

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    public void ExorcismOngoing()
rename to ProcessExorcism, refactor this so if (_accumulatedTime >= _holdTime) wont be called 2 times

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerBase.cs
> +    private enum _playerState
not used, delete this

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> + * Use Setter and Getter to access the variables.
delete this line

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> + * Is referenced in ExorcismItem.
delete this line

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void ShowBar(bool _isActive)
variable name that acts as a parameter should not have _ prefix

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void SetMinHold(float hold)
misinterpreted meaning, rename to SetSliderMinValue

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void SetHold(float hold)
misinterpreted meaning, rename to SetSliderValue

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HudManager.cs
> +        GameManager.ShowExorcismHudEvent += ShowExorcism;
update slider value through event

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        //Debug.Log("[TEST EXORCISM] Exorcism Overworld Item Found");
delete this

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        Assert.NotNull(inventory.GetActiveItem());
dont just assert not null, assert whether the active item is the one that is desired

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        //Debug.Log("[TEST EXORCISM] Exorcism Overworld Item Found");
delete this

2022-02-13 15:45 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        Assert.NotNull(inventory.GetActiveItem());
dont just assert not null, assert whether the active item is the one that is desired

2022-02-14 03:46 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    public bool GetUsed()
This is just a getter, so shouldn't it be GetIsUsed?

2022-02-14 03:47 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> + * Use Setter and Getter to access the variables.
Class docs so isn't it important? Unless you mean line 17 and 18

2022-02-14 05:38 UTC, VadimBhirawa commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        //Debug.Log("[TEST EXORCISM] Exorcism Overworld Item Found");
The debug log? Cause the ExorcismItemOW is used to locate it in the level.

2022-02-14 07:32 UTC, JahnsMichael commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +    public abstract void ButtonReleased();
I think you can move it to `ExorcismItem`, then every Item that doesn't need the `ButtonReleased` functionality doesn't have to override ButtonReleased. But because of that, there should be an error in `Inventory` because `Item` doesn't have the method. You can cast the `_activeItem` to `ExorcismItem` then call the `ButtonReleased` method. Or another solution is to make the `ButtonReleased` virtual with a blank function then the subclass/concrete class can override the method if needed. WDYT?

2022-02-14 07:35 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        //Debug.Log("[TEST EXORCISM] Exorcism Overworld Item Found");
yes, the debug log

2022-02-14 11:37 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +    public abstract void ButtonReleased();
Thank you Jahns, the 2nd solution worked. The first solution didn't seem possible to me, and after trying to implement it, I was right. An abstract function needs to be implemented in an abstract class, and `ExorcismItem` could not be an abstract class as it is referenced by a `GameObject`. The second solution worked, but what is Rafif's opinion? I'm not sure he approves of a virtual function that is referenced by only 1 class (at the current time).

2022-02-14 13:07 UTC, JahnsMichael approved these changes

2022-02-14 14:57 UTC, rafiftaris approved these changes
kereenn!!

2022-02-15 16:23 UTC, raihansyahdean requested changes

2022-02-15 16:23 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/PlayerBase.cs
> +    /*private enum _playerState
why is this commented? remove if not needed

2022-02-17 12:12 UTC, rafiftaris requested changes

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +        if (slider.gameObject.activeSelf)
redundant if

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void SetSliderMinValue(float hold)
put this on setter getter region

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void SetSliderValue(float hold)
put this on setter getter region

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void ProcessExorcism()
delete flag checker debugger

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public void ProcessExorcism()
make the flow consistent on each condition

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HudManager.cs
> +        //Debug.Log("[START EXORCISM HUD] isShowExorcism: " + isShowExorcism);
misplaced debug, delete this

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        IExorcismItem exorcismItem = exorcismItemObj.GetComponent<IExorcismItem>();
unreferenced var, delete this

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        Assert.IsFalse(exorcismSliderObj.activeSelf);
create new assert: check whether isExorcised

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        IExorcismItem exorcismItem = exorcismItemObj.GetComponent<IExorcismItem>();
unreferenced var, delete this

2022-02-17 12:12 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/ExorcismTest.cs
> +        Assert.IsFalse(exorcismSliderObj.activeSelf);
create new assert: check whether isExorcised

2022-02-18 15:24 UTC, rafiftaris requested changes

2022-02-19 11:55 UTC, rafiftaris approved these changes
kerenn finally 🥳 🎉

2022-02-19 14:10 UTC, raihansyahdean requested changes
Remove auto created init test scene in Assets/

2022-02-19 14:30 UTC, raihansyahdean requested changes

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +        ExorcismSetMinSliderEvent?.Invoke(_sliderMinValue);
no need to use set min value directly from exo item, better put on Awake() function of HudManager

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/ExorcismItem.cs
> +    public static event Action<float> ExorcismSetMinSliderEvent;
remove this event

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +
remove empty line

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/HudManager.cs
> +        ExorcismBar.ExorcismUpdateSliderEvent += UpdateSlider;
remove this

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/HudManager.cs
> +        ExorcismBar.ExorcismUpdateSliderEvent -= UpdateSlider;
remove this

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +    public static event Action<float> ExorcismUpdateSliderEvent;
remove this

2022-02-19 14:30 UTC, raihansyahdean commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
> +            ExorcismUpdateSliderEvent?.Invoke(_accumulatedTime);
Instead of calling another event and making it a cycle ExoBar -> HudManager -> ExoBar, make it just call the SetSliderValue() method

2022-02-19 14:55 UTC, raihansyahdean approved these changes

2022-02-19 14:55 UTC, merged