[feature] Implement script that plays player dies audio from GM
InShine-Studios/Horror-3D pull request #191
Opened 2022-02-13 10:33 UTC by RaiRiz

the script implemented is still a dummy class so currently it can't be tested

### Main changes

- Refactor AudioManager.cs filename to AudioPlayer.cs. Then, create an actual but dummy AudioManager class and prefab. A player dies audio event has been prepared in GameManager class. Need to wait for PlayerStates.cs to be implemented first for future uses.
- Add new sfx for player walk, player run, and ankh activation/deactivation. The place where players put their feet is assumed to be a ceramic surface.
- Each of player walk and player run sfx is divided into 2 types namely 1 step and 2 steps. Both can be used in combination, separately, or with loop according to needs.

### Tasks List

- [close #166 ]
- [close #179 ]
- [close #180 ]

### Attachments

- Refactor filename: AudioManager.cs to AudioPlayer.cs
![image](https://user-images.githubusercontent.com/55452897/153748933-1695f4e7-ea77-42d2-aeb4-6a9c42c01102.png)

- Actual but dummy AudioManager
![image](https://user-images.githubusercontent.com/55452897/153748946-5de1e0f2-59d5-4f92-996f-74636fdced57.png)

- Player walk sfx files
![image](https://user-images.githubusercontent.com/55452897/153748958-51893e39-4707-4ffc-af46-37636340ed2d.png)

- Player walk 1 step sfx on play
https://discord.com/channels/918510403909214268/918514897422258216/942359896995795014

- Player walk 2 steps sfx on play
https://discord.com/channels/918510403909214268/918514897422258216/942359182592581702

- Player run sfx files
![image](https://user-images.githubusercontent.com/55452897/153748961-64fe94bf-6652-430d-86a9-1b748a3f21d2.png)

- Player run sfx 1 step on play
https://discord.com/channels/918510403909214268/918514897422258216/942367215557169173

- Player run 2 steps sfx on play
https://discord.com/channels/918510403909214268/918514897422258216/942367194380111914

- Ankh sfx
![image](https://user-images.githubusercontent.com/55452897/153748975-2bb18d5f-8c63-4954-afaf-5360b00d5026.png)

- Ankh sfx on play
https://discord.com/channels/918510403909214268/918514897422258216/941224093175390239

- Player footstep with right foot first
https://discord.com/channels/918510403909214268/918514897422258216/942433205615747144

2022-02-13 11:49 UTC, uciii requested changes
han saran, possible gk nambah suara yang satu langkah kakinya di lari sama jalan? jadi kalo suara yang 1 langkah ini suara kak kiri, tambahin suara kaki kanannya. Biar kalo jadi pake langkah kaki yang satu satu bisa beda kanan kirinya?

atau menurut lu oke 1 suara aja, jadi kiri kanannya suaranya sama? feel free to challenge  this suggestion.

2022-02-13 11:49 UTC, uciii commented on Assets/Astralization/Scripts/Managers/AudioManager.cs
> +public class AudioManager : MonoBehaviour
class docs

2022-02-13 11:55 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/AudioManager.cs
> +    private AudioPlayer AudioPlayerObj;
oke, akan dieksekusi segera

2022-02-13 11:58 UTC, RaiRiz commented
sebetulnya 1 ragam suara yg sama utk kaki kiri dan kanan nggak apa. tapi betul sih, ada baiknya dibedakan. lebih masuk ke logika auditori-nya sekaligus membantu memberitahu pemain bahwa memang avatarnya sedang berjalan/berlari dengan melangkahkan kaki yang berbeda bergantian dan bukan selangkah2 kaki yg sama terus. akan dieksekusi segera

2022-02-13 12:11 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/AudioManager.cs
> +public class AudioManager : MonoBehaviour
yang ini gimana maksudnya?

2022-02-13 12:12 UTC, raihansyahdean requested changes
Rename audio files:
instead of 1Step better use OneStep, 2Step better TwoSteps, etc.

2022-02-13 12:22 UTC, GustiNgurahYama commented on Assets/Astralization/Scripts/Managers/AudioManager.cs
> +public class AudioManager : MonoBehaviour
bikin docs buat classnya di codenya han, jadi diatas kelas audiomanager ada semacam
```
/*
 * Class to manage bla bla bla
 */
```

2022-02-13 12:42 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    public static event Action PlayerAudioDiesEvent;
oke, akan dieksekusi segera

2022-02-13 15:25 UTC, raihansyahdean approved these changes
Nice!

2022-02-13 15:28 UTC, VadimBhirawa approved these changes
Sounds good!

2022-02-14 01:45 UTC, uciii approved these changes
LGTM

2022-02-14 03:29 UTC, merged