[feature] hide mechanic
InShine-Studios/Horror-3D pull request #192
Opened 2022-02-13 13:44 UTC by naufalhilmi12345

### Main changes

- adding implementation for hide mechanic (not full)

### Tasks List
[close #149 ]

### Attachments

https://user-images.githubusercontent.com/44135006/153755934-c8039a0d-8ce0-41d1-942c-d30cdc38cc05.mp4

2022-02-14 04:50 UTC, rafiftaris requested changes
flow dan fungsionalitas udah bagus 👍

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/InputHandler/HideInputHandler.cs
> +    public void UnHidePlayer(InputAction.CallbackContext ctx)
rename to UnhidePlayer

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HidingOverlay.cs
> +    // Start is called before the first frame update
delete this

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HidingOverlay.cs
> +    [Space]
delete this because the field above is not displayed on inspector

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HudManager.cs
> +    private HidingOverlay hidingManager;
use _ prefix

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/HudManager.cs
>      private DialogueManager dialogueManager;
use _ prefix (nitip hehe)

2022-02-14 04:50 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/InteractableTest.cs
> +    protected GameObject hud;
set to private

2022-02-14 12:36 UTC, rafiftaris approved these changes
mantaappp

2022-02-14 13:19 UTC, uciii commented on Assets/Astralization/Scripts/Player/InputHandler/HideInputHandler.cs
> +            StopHidingHudEvent?.Invoke(false);
I think it should use GM instead of direct invoke to input manager and hud manager. Wdyt?

2022-02-14 14:18 UTC, uciii approved these changes

2022-02-15 10:06 UTC, VadimBhirawa approved these changes
Niceeee!

2022-02-15 16:29 UTC, merged