[feature] Evidence Clock and SilhouetteBowl
InShine-Studios/Horror-3D pull request #205
Opened 2022-02-15 08:11 UTC by JahnsMichael

### Main changes

- add new Evidence Item, Clock and SilhouetteBowl

### Tasks List

- [close #171]
- [close #172]

### Attachments

#### Silhouette Bowl

- same state as Thermometer
- Behavior
  - Positive (Headless): Torus active
  - Negative (Heartless): Sphere active

https://user-images.githubusercontent.com/60375650/154018513-ece863c2-c796-4ba5-ace0-2fa095d687cc.mp4

#### Clock (sound on)

- same state as Thermometer
- Behavior
  - Different AudioClip for Active/Positive/Negative, and Base is silent
  - Currently using heartbeat SFX

https://user-images.githubusercontent.com/60375650/154018561-30128b0d-b82d-46c9-b047-c5351dc69ac2.mp4

2022-02-15 11:21 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-02-15 13:54 UTC, VadimBhirawa approved these changes
Seems good!

2022-02-17 02:31 UTC, rafiftaris requested changes
Nicee 👍 . Only minor changes and check docs and tc list for additional comment

2022-02-17 03:50 UTC, rafiftaris requested changes
private variables should use _ prefix

2022-02-17 06:13 UTC, JahnsMichael commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/Clock.cs
> +public class Clock : EvidenceItem
done

2022-02-17 06:25 UTC, JahnsMichael commented
> Nicee +1 . Only minor changes and check docs and tc list for additional comment

done

2022-02-17 06:25 UTC, JahnsMichael commented
> private variables should use _ prefix

done, please re-review

2022-02-17 12:22 UTC, rafiftaris approved these changes
siap merge 🚀

2022-02-18 12:45 UTC, merged