Refactored Volumes, Astral Meter Logic, and Interactables
InShine-Studios/Horror-3D pull request #206
Opened 2022-02-16 05:52 UTC by VadimBhirawa

### Main changes
Volumes:
- Created abstract class "Volumes" that has 1 virtual method and 1 abstract method
- Generalized SetState() in Volumes
- ToggleFogColor() called in Volumes

Astral Meter Logic:
- All float variables serializable
- ChangeWorld() and ToggleWorldRate() merged to just ChangeWorld()
- Renamed NPCWrongAnswer() to NpcWrongAnswer()

Interactables:
- Interactable Icons turned private and added [SerializeField]

### Tasks List
- [close #199 ]
- [close #200 ]
- [close #202 ]

### Attachments
Volumes:
- VolumeReal + VolumeAstral put inside "..Scripts/States/Volume"
![image](https://user-images.githubusercontent.com/23608044/154204013-a3a30dac-961f-4dcd-9db7-45f87bb29962.png)

AM Logic:
- All float variables serializable
![image](https://user-images.githubusercontent.com/23608044/154204134-2fca1408-0b66-4ba5-aec6-7504f513af97.png)

Interactables:
- InteractableIcon privated and serializable
![image](https://user-images.githubusercontent.com/23608044/154204471-00229551-9ae4-40d9-bda2-804b0b45433e.png)

2022-02-16 06:16 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-02-17 04:58 UTC, rafiftaris requested changes

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Interactable.cs
> +    private GameObject _InteractableIcon;
i pertama kecil

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/Volume.cs
> +    public virtual void SetState(bool state)
protected

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/Volume.cs
> +    public abstract void ToggleFogColor(bool state);
protected

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeAstral.cs
>      #region Enable - Disable
put this region on Volume class

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/AstralMeterLogic.cs
> +    [SerializeField]
add header

2022-02-17 04:58 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeAstral.cs
> +
remove this

2022-02-17 07:52 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/States/Volume/VolumeAstral.cs
>      #region Enable - Disable
I'm very sorry, but I don't think I understand what you mean? Do you mean put the Enable - Disable region on Volume class or what?

2022-02-17 12:28 UTC, rafiftaris requested changes

2022-02-17 12:28 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/AstralMeterLogic.cs
> +    [SerializeField]
ga semuanya juga dikasih header, bedain header sama tooltip. benchmark script lain

2022-02-18 15:25 UTC, rafiftaris approved these changes

2022-02-19 15:04 UTC, raihansyahdean requested changes

2022-02-19 15:04 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Interactable.cs
> +    private GameObject _interactableIcon;
make the bool UseIcon above also private and serializable

2022-02-19 15:04 UTC, raihansyahdean commented on Assets/Astralization/Scripts/States/Volume/VolumeReal.cs
> +        state = !state;
Instead of toggling it in this function, can you make the one that calls this function already use the correct bool instead?

2022-02-20 04:17 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/States/Volume/VolumeReal.cs
> +        state = !state;
One suggestion from Rafif is by using State Pattern, but it's apparently too big for this issue, so that will be done on the next sprint.

2022-02-20 08:32 UTC, raihansyahdean approved these changes

2022-02-20 08:35 UTC, merged