[refactor] State Pattern 1.0
InShine-Studios/Horror-3D pull request #208
Opened 2022-02-19 13:47 UTC by uciii

### Main changes
With this PR, we can easily control the current player state and transition to another player state dynamically. All input action is now handled by the Input manager (inherit state manager) and passes through to the current state then finally processed by correspondent function. This PR also contains changes "Player" action map to the "Default" action map.

Modified class
- InputManager: modified that inherit state manager

Added classes
- PlayerState: implement state class (base for player state)
- InitState: implement PlayerState, Initial player state (currently no usage implemented)
- DefaultPlayerState: implement PlayerState, Handle all input for the "Default" action map (when exploring phase)
- DialogueState: implement PlayerState,  Handle all input for the "Dialogue" action map (when interaction with NPC)
- HidingState: implement PlayerState, currently no usage, Handle all input for the "Hiding" action map (when player hide)

### Tasks List
- [close #197]

2022-02-20 10:01 UTC, JahnsMichael commented on Assets/Astralization/Scripts/_Common/DialogueState.cs
> +        Debug.Log("aaaa");
is this Debug necessary? if it is not I think it can be removed.
```suggestion

```

2022-02-20 10:22 UTC, JahnsMichael requested changes
There are minor suggestions. Besides that, I want to ask some questions.
- Is there any reason to move `AnkhItem.cs` to `EvidenceItem/AnkhItem.cs` ?
- Why are `.*State.cs` files located in the `_Common/` directory? I think it is more related and specific to `Player` and all handlers used in the State class are located in `Player` directory.

2022-02-20 10:22 UTC, JahnsMichael commented on Assets/Astralization/Scripts/_Common/DefaultPlayerState.cs
> +    #region Movement Variables
More like `Handler Variables` instead of `Movement Variables` because the attribute is not only about movement. wdyt? 
```suggestion
    #region Handler Variables
```

2022-02-20 10:22 UTC, JahnsMichael commented on Assets/Astralization/Scripts/_Common/DialogueState.cs
> +        Debug.Log("aaaa");
Is this debug line necessary? If yes please make it more clear and descriptive or use `PrintDefaultLog`, else I think it can be removed.

```suggestion

```

2022-02-20 12:34 UTC, rafiftaris commented on Assets/Astralization/Scripts/_Common/DefaultPlayerState.cs
> +    #region Movement Variables
i agree, handler is good and more general naming

2022-02-20 12:42 UTC, rafiftaris commented on Assets/Astralization/Scripts/_Common/DialogueState.cs
> +        Debug.Log("aaaa");
actually this function is unused so i'll delete this

2022-02-20 12:44 UTC, rafiftaris commented
- `AnkhItem.cs` is not supposed to be inside EvidenceItem folder, so it will be moved
- States scripts are also moved to `Scripts/Player/States` folder

Thank you

2022-02-20 13:01 UTC, JahnsMichael approved these changes
no more issue from me, approved

2022-02-20 13:23 UTC, naufalhilmi12345 requested changes
Overall the code its good, but there is minor comment

2022-02-20 13:23 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Player/Detectors/ObjectDetector.cs
> +        //Interactable closest = GetClosestInteractable(colliders);
is this comment necessary? I think this comment can be deleted because closest variable already assign in line 54, WDYT?

2022-02-22 03:13 UTC, naufalhilmi12345 approved these changes

2022-02-22 03:21 UTC, naufalhilmi12345 requested changes
Overall the code its good, but there is minor comment

2022-02-22 03:29 UTC, raihansyahdean requested changes

2022-02-22 03:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +
empty line can be deleted

2022-02-22 03:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/States/DefaultPlayerState.cs
> +        _itemDetector = GetComponentInChildren<ItemDetector>();
reorder assignments according to variables above

2022-02-22 03:29 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/States/DefaultPlayerState.cs
> +    private PlayerMovement _playerMovement;
reorder variables according to uses, create Headers:
Movement and rotation should be first, then inventory system and detectors last. Makes it easier to see

2022-02-22 05:15 UTC, naufalhilmi12345 approved these changes

2022-02-22 07:51 UTC, raihansyahdean approved these changes

2022-02-22 07:51 UTC, merged