[refactor] HM and GM
InShine-Studios/Horror-3D pull request #221
Opened 2022-02-24 13:46 UTC by naufalhilmi12345

### Main changes

- Refactor GM
- Refactor connection between GM and HM
- Refactor ExorcismBar.cs

### Tasks List

- [close #212]

### Attachments

![image](https://user-images.githubusercontent.com/44135006/155535776-60df14b3-ade2-4f05-8ba8-3ad4bf6191fc.png)
![image](https://user-images.githubusercontent.com/44135006/155535824-b89cae21-4b59-4b68-b480-d548fd8e3584.png)
![image](https://user-images.githubusercontent.com/44135006/155535874-7b3f9d73-241b-4192-8616-0865464844f3.png)

2022-02-24 14:38 UTC, rafiftaris requested changes

2022-02-24 14:38 UTC, rafiftaris commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +        HudMapEvent?.Invoke("Dialogue", true);
strings that represents state name can be refactored. store this string in a static const field inside each state class. Variable name for this field is "name"

2022-02-24 14:41 UTC, raihansyahdean requested changes
Some changes

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    public void InvokePlayerState()
Rename function to: ResetPlayerState()

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +        PlayerActionMapEvent?.Invoke("Dialogue");
Rename event PlayerActionMapEvent to: PlayerStateEvent

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    public static event Action<string, bool> HudMapEvent;
Rename event HudMapEvent to HudEvent

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/HudManager.cs
> +    public void SetActiveHud(string hudMap, bool state)
Rename function: SetHudState(string hudKey, bool condition)

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +        HudMapEvent?.Invoke("Exorcism", true);
Make a single function: SendHudEvent(string, bool) to specifically call the invoke method. Use in all other methods

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +        PlayerActionMapEvent?.Invoke("Exorcism");
Similarly, make a single function: SendPlayerStateEvent(string) to specifically call the invoke method. Use in all other methods

2022-02-24 14:41 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    public void InvokeDialogueState()
Create regions for InvokeFunctions and SendEvents

2022-02-25 08:25 UTC, JahnsMichael approved these changes
there is no issue from me. good job!

2022-02-26 11:45 UTC, raihansyahdean approved these changes
Great work

2022-02-27 03:44 UTC, rafiftaris approved these changes
mantapp no problem

2022-02-27 07:38 UTC, merged