[refactor] refactor hide exocirsm handler
InShine-Studios/Horror-3D pull request #223
Opened 2022-02-26 07:56 UTC by naufalhilmi12345

### Main changes

- Implement state pattern for hide and exorcism handler

### Tasks List
[close #213]

### Attachments
All test pass:
![image](https://user-images.githubusercontent.com/44135006/155835234-755d929c-9884-4a86-9910-92834b7f39b5.png)

2022-02-27 03:43 UTC, rafiftaris requested changes
move GM's enum to HudManager and InputManager

2022-02-27 04:46 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/GameManager.cs
>          //Debug.Log("[INVOKE PLAYER STATE] Player state: " + state);
delete this line since it won't be used again

2022-02-27 04:48 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/GameManager.cs
>          //Debug.Log("[INVOKE PLAYER STATE] Player state: " + state);
delete this line since it won't be used again (no "state" var argument anymore)

2022-02-27 04:50 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Managers/GameManager.cs
>          //Debug.Log("[INVOKE PLAYER STATE] Player state: " + state);
how about if i change the debug log to "[INVOKE PLAYER STATE] Player state" insteadof delete that line?

2022-02-27 05:08 UTC, RaiRiz commented on Assets/Astralization/Scripts/Managers/GameManager.cs
>          //Debug.Log("[INVOKE PLAYER STATE] Player state: " + state);
that would be good too

2022-02-27 05:11 UTC, RaiRiz commented on Assets/Astralization/Scripts/Player/InputManager.cs
>      private PlayerState tempCurrentState;
should be `private PlayerState _tempCurrentState` instead; don't forget to check anything that references to this var

2022-02-27 05:38 UTC, RaiRiz approved these changes
all good from me!

2022-02-27 06:39 UTC, uciii approved these changes
looks good

2022-02-27 15:36 UTC, raihansyahdean requested changes
I think it is better to put the states enum in Utils. What do you guys think?

2022-02-28 08:31 UTC, rafiftaris approved these changes
mantaappp

2022-03-01 03:21 UTC, raihansyahdean approved these changes
Nice

2022-03-01 03:21 UTC, merged