[Refactor] Closest Interactable Calculation
InShine-Studios/Horror-3D pull request #224
Opened 2022-02-26 08:28 UTC by rafiftaris

### Main changes
- Refactor closest interactable calculation
- Adjust debug log message format
- Reorder regions

### Tasks List
- [close #214 ]
- [close #215 ]

### Attachments
![IMG_0358](https://user-images.githubusercontent.com/51603162/155836211-712ce483-0ff5-4058-b122-d82478a8ef38.jpg)

2022-02-26 13:01 UTC, raihansyahdean requested changes
Overall its already good refactors, some small changes are required though.

Also added note:
ALL functions should stay in a region (even if thet region currently only have one function)

2022-02-27 04:32 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ItemLogo.cs
> +    #region SetGet
i think UpdateLogo works like setting visibility state and its sprite, so it is a setter

2022-02-28 01:24 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-03-01 15:02 UTC, raihansyahdean approved these changes
Well done!

2022-03-01 15:02 UTC, merged