Uci/feature/dialogue choice
InShine-Studios/Horror-3D pull request #244
Opened 2022-03-04 06:54 UTC by uciii

### Main changes
```
Clearly and concisely describe the feature(s) that you developed.
```

### Tasks List
```
Link your Card to the PR by adding description: KEYWORD #CARD-NUMBER >
- close - For issues regarding creating new feature
- fix - For issues regarding bug fixes
- resolve - For issues regarding merge conflicts

Example : [close #10]
```

### Attachments
```
Screenshot(s) / short video(s) about the feature(s) result that you developed.
```

### New Packages
```
List of new packages that you use to developed the feature(s)
```

### Resources 
```
List of url(s) used to developed the feature(s)
```

2022-03-08 04:36 UTC, rafiftaris requested changes
Good implementation, just minor changes needed

2022-03-08 04:36 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/InputManager.cs
> +        //switch (ctx.action.name)
remove this, handler function should be called from ui input button callbacks, for example pressing button

2022-03-08 04:36 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/UiState.cs
> +public class UiState : PlayerState
class docs

2022-03-08 23:45 UTC, rafiftaris approved these changes
lgtm

2022-03-10 04:29 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-03-11 08:14 UTC, raihansyahdean requested changes

2022-03-11 08:14 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/PlayerStates/InputManager.cs
> +        if (actionMap.ToString().Equals("Dialogue"))
I dont think this is necessary, we can instead change the states in the utils to "UI"

2022-03-11 08:14 UTC, raihansyahdean commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
> +using UnityEngine.UI;
rename class and scene to VictimTest

2022-03-11 08:14 UTC, raihansyahdean commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
>          GameObject npc = GameObject.Find("NPC");
rename local variables to victim as well

2022-03-11 08:14 UTC, raihansyahdean commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
>          INpcController npcController = npc.GetComponent<INpcController>();
rename class to IVictimController and VictimController. Dont forget to adjust the scenes as well

2022-03-11 08:17 UTC, raihansyahdean commented on Assets/Astralization/Tests/NpcTest/NpcInteractableTest.cs
>          INpcController npcController = npc.GetComponent<INpcController>();
the action inside the class should also be renamed: VictimInteractionEvent

2022-03-12 14:05 UTC, raihansyahdean approved these changes
Excellent

2022-03-12 15:59 UTC, rafiftaris approved these changes
kereeenn

2022-03-13 02:55 UTC, merged