[feature] cooldown
InShine-Studios/Horror-3D pull request #246
Opened 2022-03-06 11:17 UTC by naufalhilmi12345

### Main changes

- adding cooldown helper

### Tasks List

- [close #231] 

### Attachments
![image](https://user-images.githubusercontent.com/44135006/156920691-21294397-242e-4712-8311-e6ff6278c085.png)

2022-03-06 13:07 UTC, raihansyahdean requested changes

2022-03-06 13:07 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +            return (_accumulatedTime >= _holdTime);
if there is this logic then I dont see the use of IsFinished bool. I think that every time the accumulated time is added, we should directly check if the timer has already finished or not and then set the IsFinished bool. The IsFinished bool should also be private and have its own setter getter. Wdyt?

2022-03-07 02:31 UTC, VadimBhirawa requested changes

2022-03-07 02:31 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/UI/ExorcismBar.cs
>      private float _accumulatedTime = 0f;
Unused variable. _accumulatedTime already in CooldownHelper. Delete this.

2022-03-07 02:31 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +        private float _accumulatedTime = 0f;
Just in case and because it's a float, add SerializeField.

2022-03-07 02:31 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +        private float _holdTime;
SerializeField too.

2022-03-07 06:12 UTC, rafiftaris requested changes
remove all SerializeField since CooldownHelper wont be a component of GameObject

2022-03-07 06:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +        private float _accumulatedTime = 0f;
don't make this SerializeField because accumulator variable is not supposed to be modifiable

2022-03-07 06:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +        private float _holdTime;
rename variable to _duration for generalization of cooldown usage

2022-03-07 06:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/Utils/CooldownHelper.cs
> +        public CooldownHelper(float holdTime)
rename holdTime

2022-03-07 10:28 UTC, VadimBhirawa approved these changes
LGTM! NICE!

2022-03-07 10:44 UTC, raihansyahdean approved these changes
Nicely done

2022-03-08 02:45 UTC, rafiftaris approved these changes

2022-03-08 02:50 UTC, merged