[refactor] player reposition when hiding
InShine-Studios/Horror-3D pull request #253
Opened 2022-03-10 16:24 UTC by naufalhilmi12345

### Main changes

- Adding move inside closets when hiding

### Tasks List

- [close #232] 

### Attachments

https://user-images.githubusercontent.com/44135006/157708143-e3feae70-58d2-4922-ba7a-35c77d82afc7.mp4

2022-03-11 02:45 UTC, rafiftaris requested changes
the reposition is so smooth dangg!!

2022-03-11 02:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        Vector3 calOffset = _closets.transform.parent.rotation * new Vector3(0.97f,1.1f,-0.47f);
manual offset may not be suitable for closets with other sizes, calculate the offset based on closet's model size

PS: gua udah tau kodingannya tapi gua mau lu coba cari sendiri yam wkwk

2022-03-11 02:45 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        _playerMovementConditions = !_playerMovementConditions;
delete this variable, langsung toggle aja playerMovementnya

2022-03-11 02:55 UTC, rafiftaris requested changes

2022-03-11 02:55 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +    [Tooltip("PlayerMovement object that gonna be toogled")]
ini script bukan object wkwk

2022-03-11 03:17 UTC, VadimBhirawa approved these changes
Rafif already mentioned most of the comments I'm about to comment, so approved!

2022-03-11 08:25 UTC, raihansyahdean requested changes
The hiding overlay is visibile before and after the animation, please make the object inactive when not transitioning. Activate it before the animation starts.

2022-03-11 08:48 UTC, rafiftaris requested changes
[BUG] spammable hiding bikin player nyangkut, kasih delay aja gabisa hide/unhide pas lagi transisi

2022-03-11 08:48 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        this.transform.Find("Glow").GetComponent<Light>().enabled = false;
put finding component process at awake, so it wont run multiple times

2022-03-11 08:48 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        _closets = GetComponentInChildren<InteractableDetector>().GetClosest().transform.parent;
put finding component process at awake, so it wont run multiple times

2022-03-11 08:48 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        this.transform.Find("Glow").GetComponent<Light>().enabled = true;
put finding component process at awake, so it wont run multiple times

2022-03-11 09:53 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +        _closets = GetComponentInChildren<InteractableDetector>().GetClosest().transform.parent;
i already put them in awake before but it make player cannot hide more than one because the hiding state is awake one time

2022-03-13 09:32 UTC, rafiftaris approved these changes
Mantapp 👍👍👍

2022-03-13 12:51 UTC, raihansyahdean approved these changes
Well done

2022-03-13 12:51 UTC, merged