[rework] third person camera view
InShine-Studios/Horror-3D pull request #254
Opened 2022-03-11 01:33 UTC by rafiftaris

### Main changes
- rework Player Follow camera
- rework player animation system

### Tasks List
- [close #233 ]

### Attachments

https://user-images.githubusercontent.com/51603162/157784643-b373392a-00da-49b5-a37c-e63d9d5f50df.mp4

2022-03-11 06:47 UTC, JahnsMichael reviewed
I think the camera rotation is too sensitive, wdyt? Here is the recording for comparison between how much the camera was rotated and how much my mouse pointer was moved.

https://user-images.githubusercontent.com/60375650/157816313-bee91cef-f046-48ab-868b-6550eb72aee5.mp4

2022-03-13 03:58 UTC, naufalhilmi12345 approved these changes
Its good for mee! Cool

2022-03-14 12:55 UTC, raihansyahdean requested changes
- Adjust line endings: UiHelper.cs
- Make Utils subfolders (Calculation, Helpers, etc.) Naming is up to you
- Delete init test scene

2022-03-14 12:55 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Player/PlayerStates/HidingState.cs
> +            StartCoroutine(Utils.DelayerHelper.Delay(1.0f, () => StopHidingEvent?.Invoke()));
Make use owner.changestate

2022-03-14 14:43 UTC, raihansyahdean approved these changes
Nice camera rework

2022-03-14 14:44 UTC, merged