[bugfix] interactables and hiding
InShine-Studios/Horror-3D pull request #278
Opened 2022-03-17 05:01 UTC by rafiftaris

### Main changes
```
Clearly and concisely describe the feature(s) that you developed.
```

### Tasks List
```
Link your Card to the PR by adding description: KEYWORD #CARD-NUMBER >
- close - For issues regarding creating new feature
- fix - For issues regarding bug fixes
- resolve - For issues regarding merge conflicts

Example : [close #10]
```

### Attachments
```
Screenshot(s) / short video(s) about the feature(s) result that you developed.
```

### New Packages
```
List of new packages that you use to developed the feature(s)
```

### Resources 
```
List of url(s) used to developed the feature(s)
```

2022-03-19 14:05 UTC, raihansyahdean requested changes

2022-03-19 14:05 UTC, raihansyahdean commented on Assets/Astralization/Scripts/Interactables/Controller/DoorController.cs
> +        return isTransitioning;
Isn't this function only called when interacted by the player? The bool value returned will not be exactly as the animation finishes then right? I think you should implement this via a yield function (like in StateMachine when changin states)

2022-03-24 12:42 UTC, InShineStudios approved these changes

2022-03-24 12:44 UTC, raihansyahdean approved these changes

2022-03-24 12:45 UTC, merged