[refactor] implement evidence state
InShine-Studios/Horror-3D pull request #291
Opened 2022-03-23 09:14 UTC by naufalhilmi12345

### Main changes

- Implement state pattern for evidence item

### Tasks List

- [close #234]  
- [close #285]
- [close #270]
- [close #286]

### Attachments
![image](https://user-images.githubusercontent.com/44135006/159663962-0b962fad-4b33-45fa-8b40-3cb6ffa1e570.png)

2022-03-25 01:31 UTC, rafiftaris requested changes

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockStates/ClockState.cs
> +        AudioSource audioSource = _audioSourceReference.GetComponent<AudioSource>();
make the AudioSource as the class variable instead of the gameobject, so GetComponent is not running on every state changes

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlActiveState.cs
> +        Debug.Log(positiveModel);
delete this debug

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlInactiveState.cs
> +        Debug.Log(positiveModel);
delete this debug

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlManager.cs
> +    #region Getter
rename region to SetGet

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerItem.cs
> +    public override void Use()
put this on the same region as OnInteraction

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerItem.cs
>      #region Evidence related
rename to EvidenceHandler

2022-03-25 01:31 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerStates/ThermometerState.cs
> +        MeshRenderer mesh = transform.Find("Model").GetComponentInChildren<MeshRenderer>(true);
make this variable as class variable

2022-03-25 12:52 UTC, InShineStudios requested changes
- Change InputManager _currentPlayerState
- In EvidenceItemTestScene --> Put evidence items as child of OverworldItems GO
- Move materials and audios used for state changes to Resources/EvidenceItem/...
- Rename SFX_Heartbeat_X to SFX_Clock_X

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockStates/ClockState.cs
> +        _audioSourceReference = transform.Find("AudioPlayer/StateAudio").gameObject;
rename: _audioSourceReference to StateAudio

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlItem.cs
> +    #region Use
rename region: ItemInputHandler
move OnInteraction() and OnGhostInteraction() functions to this region

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlItem.cs
>      #region Evidence related
rename region: EvidenceHelper

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockStates/ClockManager.cs
> +    private ClockState _currentClockState;
remove this var change to local

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockStates/ClockManager.cs
> +    public override void ChangeState<T>()
remove this function

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockStates/ClockManager.cs
> +        return _currentClockState;
return (ClockState)CurrentState

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlManager.cs
> +    private SilhouetteBowlState _currentSilhouetteBowlState;
remove this variable

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlManager.cs
> +        return _currentSilhouetteBowlState;
return (SilhoueteBowlState)CurrentState

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/SilhouetteBowlStates/SilhouetteBowlManager.cs
> +    public override void ChangeState<T>()
remove this function

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerStates/ThermometerManager.cs
> +    private ThermometerState _currentThermometerState;
remove variable

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerStates/ThermometerManager.cs
> +        return _currentThermometerState;
return (ThermometerState)CurrentState

2022-03-25 12:52 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ThermometerStates/ThermometerManager.cs
> +    public override void ChangeState<T>()
remove function

2022-03-26 07:36 UTC, rafiftaris requested changes
ketinggalan satu wkwk, secara fungsional udah oke

2022-03-26 07:36 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/EvidenceItem/ClockItem.cs
> +        base.OnInteraction();
put base function call first on every overridden function

2022-03-26 16:07 UTC, RaiRiz approved these changes
LGTM!

2022-03-28 05:45 UTC, InShineStudios approved these changes
Well done

2022-03-28 07:26 UTC, rafiftaris approved these changes
huge refactor done well!! 👍

2022-03-28 15:09 UTC, merged