[refactor] ghost states
InShine-Studios/Horror-3D pull request #292
Opened 2022-03-24 07:06 UTC by rafiftaris

### Main changes
- refactor ghost movement into ghost states (idle & wander state)
- add empty ghost state for future development (chasing state)

### Tasks List
- [close #249 ]
- [close #250 ]

2022-03-26 12:16 UTC, naufalhilmi12345 approved these changes
LGTM! Cool

2022-03-26 12:39 UTC, JahnsMichael approved these changes
The test passed and I think there is no issue with the code. LGTM!

2022-03-28 12:45 UTC, InShineStudios requested changes

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostMovement.cs
> +        _stageManager = GameObject.Find("Stage/StageManager").GetComponent<StageManager>();
Add new static function in StageManager to get the desired world point

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostManager.cs
> +public class GhostManager : StateMachine, IGhostManager
Rename class: GhostStateMachine

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/IdleGhostState.cs
> +            Quaternion delta = Utils.GeometryCalcu.GetAngleDelta(transform.rotation, targetRotation);
Extract to a method

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/IdleGhostState.cs
> +    public override void Enter()
enter and exit in region GhostStateHandler

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/IdleGhostState.cs
> +    private void ChangeToWanderInSeconds(float delay)
make separate region

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/InitGhostState.cs
> +    #region Handler
rename region: Initialization
Rename also in InitPlayerState and InitEvidenceState.

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/WanderGhostState.cs
> +    private Utils.CooldownHelper _checker;
Rename _checker to _wanderTimer

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/WanderGhostState.cs
> +    #region Handler
region: GhostStateHandler

2022-03-28 12:45 UTC, InShineStudios commented on Assets/Astralization/Scripts/Ghost/GhostStates/WanderGhostState.cs
> +    private void StartWandering()
Rename: GhostWander()
Separate region: WanderingHandler

2022-03-29 01:48 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostMovement.cs
> +        _stageManager = GameObject.Find("Stage/StageManager").GetComponent<StageManager>();
<img width="524" alt="image" src="https://user-images.githubusercontent.com/51603162/160516020-c3bc7697-3b13-4399-bcb6-16a06763f83d.png">

this function cant be static because _roomPoints also needs to be static but the room points themselves are loaded in runtime, therefore cant be static

2022-03-30 02:47 UTC, InShineStudios approved these changes
Nicely done

2022-03-30 02:47 UTC, merged