[rework] camera
InShine-Studios/Horror-3D pull request #301
Opened 2022-03-29 17:31 UTC by rafiftaris

### Main changes
- remove zoom effects on camera (adjust cinemachine camera rigs)
- lock cursor position when player is not in ui state
- release cursor lock when player is in ui state

### Tasks List
- [close #287 ]

### Attachments

https://user-images.githubusercontent.com/51603162/160670864-192aa1eb-be10-488d-be66-6855b641e3a9.mp4

2022-03-31 14:10 UTC, JahnsMichael approved these changes
LGTM!!

2022-04-02 01:48 UTC, RaiRiz approved these changes
Good to go!

2022-04-02 14:02 UTC, InShineStudios requested changes

2022-04-03 16:03 UTC, InShineStudios approved these changes
Nice

2022-04-03 16:03 UTC, merged