[refactor] World State Using State Pattern
InShine-Studios/Horror-3D pull request #302
Opened 2022-03-31 15:12 UTC by VadimBhirawa

### Main changes
Refactored world state (volumes) into using State Pattern.

### Tasks List
- [close #239 ]

2022-04-01 08:26 UTC, rafiftaris requested changes

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +        //Debug.Log("[MANAGER] Changing world state to " + (_isInAstralWorld ? "Astral" : "Real"));
update debug message

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/AstralMeterLogic.cs
> +        _isInAstralWorld = !_isInAstralWorld;
use information from States instead of from events

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeAstralState.cs
> +    #region Handler
rename region to StateHandler

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/InitVolumeState.cs
> +    #region Handler
rename region to StateHandler

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeRealState.cs
> +    #region Handler
rename region to StateHandler

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeState.cs
> +    #region Handler
rename region to StateHandler

2022-04-01 08:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/Volume/VolumeState.cs
> +}
add newline

2022-04-01 08:43 UTC, rafiftaris requested changes
- rename "Volume" to World as AstralMeterLogic also needs to see the current WorldState

2022-04-03 05:05 UTC, rafiftaris requested changes
AstralMeterLogic.cs: rename _astralMeter to _currentMeter

2022-04-03 05:05 UTC, rafiftaris commented on Assets/Astralization/Scripts/States/WorldState/WorldStateMachine.cs
> +    public WorldState GetCurrentState()
ini dipake dimana?

2022-04-03 14:42 UTC, rafiftaris approved these changes
LGTM!

2022-04-03 15:58 UTC, RaiRiz approved these changes

2022-04-04 00:45 UTC, rafiftaris requested changes
AstralMeterLogic.cs: rename _astralMeter to _currentMeter

2022-04-04 06:58 UTC, rafiftaris approved these changes

2022-04-04 13:47 UTC, merged