[feature] adding implementation for kill phase
InShine-Studios/Horror-3D pull request #316
Opened 2022-04-10 09:14 UTC by naufalhilmi12345

### Main changes

- Adding random kill phase 

### Tasks List

- [close #307]

### Attachments

https://user-images.githubusercontent.com/44135006/162611264-da4508bc-be73-4e25-8eec-505a9e1dc8c1.mp4

2022-04-10 16:23 UTC, rafiftaris requested changes
naming udah jelas mantap 👍

general request: beberapa variable/function encapsulation type masih salah, coba dibenerin

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Tests/GhostTest/GhostTest.cs
> +        yield return new WaitWhile(ghostMovement.IsOnRoute);
ini buat apa?

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Tests/GhostTest/GhostTest.cs
> +        Assert.True(volumeReal.activeInHierarchy);
also check whether WorldState is WorldAstralState or WorldRealState

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> +    #region SetGet
region setget dulu baru monobehaviour

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> +    private Utils.CooldownHelper _graceTimer;
actually cooldownhelper itu implementasi yang jelek wkwk, yang ini diskusi di discord aja enakan

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> +    #region Handler
rename to KillPhaseHandler

2022-04-10 16:23 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> +        if (randomResults > 0.5f)
set threshold value into serializablefield

2022-04-12 04:03 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> +    private IEnumerator KillPhaseTimer()
rename to StartKillPhase

2022-04-12 04:13 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
> -    private void Awake()
tetep perlu awake buat ngejalanin coroutine sesuai dengan kondisi _isKillPhase dan _isGrace di awal

2022-04-14 14:42 UTC, RaiRiz approved these changes

2022-04-15 09:28 UTC, rafiftaris approved these changes

2022-04-16 08:08 UTC, merged