[feature] ghost chasing
InShine-Studios/Horror-3D pull request #321
Opened 2022-04-19 07:53 UTC by rafiftaris

### Main changes
- add ghost ability to see player
- add ghost ability to unstuck itself from area between rooms
- add GhostTransitionZone in StageBuilder and ScriptableObject
- integrate ghost chasing state with killing phase

### Tasks List
- [close #150 ]
- [close #305 ]

### Attachments

https://user-images.githubusercontent.com/51603162/163953376-630e95ed-240b-4412-a1a0-51f423fde57c.mp4

**Debug material**
- yellow: idle state
- orange: wandering state
- blue: chasing state

2022-04-21 15:57 UTC, naufalhilmi12345 requested changes
Overall the code is good, but there is one thing that i wanna ask.

2022-04-21 15:57 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/Managers/Stage System/GhostTransitionZone.cs
> +    public void SetZonePosition(Vector3 pos)
Sorry i wanna ask about ZonePosition and ZoneLocalPosition. What is the difference between those two? because i think its the same thing.

2022-04-22 08:56 UTC, rafiftaris commented on Assets/Astralization/Scripts/Managers/Stage System/GhostTransitionZone.cs
> +    public void SetZonePosition(Vector3 pos)
position biasa itu position terhadap world sedangkan localposition itu position terhadap parent. kalo ghost mau baca posisi harus pake position tapi kalo stagebuilder mau nentuin instantiated zoneposition itu harus pake localposition

2022-04-22 09:09 UTC, VadimBhirawa reviewed
I just have a few questions. Other than that, everything else is already good!

2022-04-22 09:09 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Ghost/GhostFieldOfView.cs
> +    private const float _checkRate = 0.2f;
I just want to ask, if this rate is already handled by GhostManager, what does this one do and does it have to be there?

2022-04-22 09:09 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
>      private bool _isKillPhase = false;
This is just another question, is it better for the bool "Kill Phase" checker to be on GhostManager or GameManager? Because in my opinion, Kill Phase affects the whole game, not just the ghost (unless other components like players etc references GhostManager for the Kill Phase).

2022-04-22 09:12 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostFieldOfView.cs
> +    private const float _checkRate = 0.2f;
itu udah ga kepake, lupa didelete wkwk

2022-04-22 09:13 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
>      private bool _isKillPhase = false;
untuk sekarang kayaknya belom butuh karena kill phase masih seputar ghost, nanti kalo udah integrasi sama Astral Meter baru dipindah ke GameManager

2022-04-22 09:24 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Ghost/GhostFieldOfView.cs
> +    private const float _checkRate = 0.2f;
oh I see wkwkkw

2022-04-22 09:24 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Ghost/GhostManager.cs
>      private bool _isKillPhase = false;
Sipsip, udah berarti, approved

2022-04-22 09:25 UTC, VadimBhirawa approved these changes
Everything looks good enough!

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostFieldOfView.cs
> +    private const float _checkRate = 0.2f;
remove unused variable (cek pake VS)

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostChasingState.cs
> +    protected string _wanderTarget;
remove unused var

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostChasingState.cs
> +    protected bool _isShifted;
remove unused var

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostWanderState.cs
> +    protected GhostMovement _ghostMovement;
set to private

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostWanderState.cs
> +    protected string _wanderTarget;
set to private

2022-04-22 16:30 UTC, rafiftaris commented on Assets/Astralization/Scripts/Ghost/GhostStates/GhostWanderState.cs
> +    protected bool _isShifted;
set to private

2022-04-24 07:11 UTC, InShineStudios requested changes
And adjust class names for state pattern (refer to drawio)

2022-04-29 11:37 UTC, VadimBhirawa approved these changes
Everything looks good!

2022-04-29 11:43 UTC, naufalhilmi12345 approved these changes
LGTM! Cool

2022-05-05 09:24 UTC, InShineStudios approved these changes

2022-05-05 09:24 UTC, merged