[rework] inventory hud
InShine-Studios/Horror-3D pull request #335
Opened 2022-05-07 03:49 UTC by rafiftaris

### Main changes
- item slot hud
- item hud manager
- tween on item slot hud
- bugfix on item detector: item is not removed from nearby interactables after picked, creating duplicates when discarding

### Tasks List
- [close #315 ]

### Attachments
https://user-images.githubusercontent.com/51603162/167237049-da619e77-85a5-4afb-9413-40e1de2cbcad.mp4

### New Packages
- [Unity-tweens](https://github.com/jeffreylanters/unity-tweens.git)

2022-05-11 12:48 UTC, uciii commented on Assets/Astralization/Scripts/UI/Drawer/CircleGraphic.cs
> +}
EoF

2022-05-12 02:40 UTC, naufalhilmi12345 requested changes
LGTM for implementation. there is one question for the code

2022-05-12 05:15 UTC, VadimBhirawa requested changes
It already looks pretty good, but I would add some extras:
- Maybe add a function so that when the hud is expanded, players can press Tab to close the hud (some people would expand just to check what items they're bringing).
- The duration of the expansion (hud expand), is 2s, but should refresh when players change the active item slot (either via scroll or via quickslot).

2022-05-12 07:09 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +    private int _size = 3;
nama class udah inventory, kalo variable ada kata2 inven lagi jadi redundant menurut gua. Kalo mau akses variable itu, Inventory.Size lebih enak dibaca daripada Inventory.SizeInven kan?

2022-05-13 04:20 UTC, rafiftaris commented on Assets/Astralization/Scripts/Interactables/Item/Item.cs
> +    protected Sprite _HudLogo;
remove underscore

2022-05-13 04:20 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ItemHud/ItemHudDisplay.cs
> +    private ItemSlot[] itemSlots;
add underscore on private

2022-05-15 09:42 UTC, VadimBhirawa approved these changes
It all looks good now!

2022-05-15 09:55 UTC, naufalhilmi12345 approved these changes
Cool! LGTM

2022-05-15 13:17 UTC, merged