[rework] player camera placement and model animation of iris
InShine-Studios/Horror-3D pull request #344
Opened 2022-05-26 17:43 UTC by rafiftaris

### Main changes
- created "Player" prefab, a combination of fully functioning character body and camera that follows the character body
- implemented CameraOffset.cs to Player Camera so center of camera orbit can be shifted
- implemented PlayerAnimation.cs, a script that manages player animation (biar lebih keintegrasi daripada getcomponent<animator> mulu). Old player animation script is renamed to PlayerAnimation2D.cs
- 

### Tasks List
- [close #326 ]

### Attachments
<img width="207" alt="image" src="https://user-images.githubusercontent.com/51603162/170544362-9abb1048-6d0a-421d-87ff-4e2c515e2eba.png">

https://user-images.githubusercontent.com/51603162/170545107-31a18cc0-742b-4d8b-bb1b-7e4d6e9bc260.mp4

2022-05-28 04:10 UTC, VadimBhirawa requested changes
Other than the issues addressed in the discord, I'd like some feedback from these comments I have. Everything else looks good enough though.

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Camera/CameraOffset.cs
> +}
Add new line at the end

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerBase.cs
> +    //float GetRotationSpeed();
If this isn't used later on, maybe delete this? Or if this might be used later maybe add comment or debug?

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerBase.cs
> +    //[SerializeField] private float _rotationSpeed;
If this isn't used, maybe delete too?

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerBase.cs
> +    //public float GetRotationSpeed()
Maybe this too? If this might be used later, maybe add an extra comment or debug?

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerMovement.cs
> +        //_animation.transform.rotation = Quaternion.Euler(0f, _moveAngle, 0f);
This too? (Delete if unused)

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerMovement.cs
> +            //_animation.SetSpriteMovingDirection(_faceDirection);
This too?

2022-05-28 04:10 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/PlayerMovement.cs
> +            //_animation.SetSpriteIdleDirection(_rotatable.transform, _mainCamera.transform);
This too?

2022-05-28 08:46 UTC, InShineStudios requested changes
Good work, a few minor reviews adding to Vadim's review

2022-05-28 08:46 UTC, InShineStudios commented on Assets/Astralization/Scripts/Player/PlayerAnimation2D.cs
> +}
new line, is this script the old script for 2D animation that holds perspective to the camera? If so i think you should rename it to "PlayerSpriteAnim"

2022-05-28 08:46 UTC, InShineStudios commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerDefaultState.cs
> +        //Debug.Log("Mouse delta value: " + ctx.ReadValue<Vector2>());
The mouse delta function doesn't have any lines of code? Maybe add the previous line but commented and explanation to it?

Or remove it completely from the DefaultState as it is useless?

2022-06-06 08:22 UTC, uciii approved these changes
LG for functionality

2022-06-06 12:56 UTC, InShineStudios approved these changes

2022-06-06 12:57 UTC, merged