[rework] Inventory: Make Item class NOT a child of interactable class
InShine-Studios/Horror-3D pull request #345
Opened 2022-05-28 04:18 UTC by VadimBhirawa

### Main changes
Interactable.cs:
- AudioPlayerObj dijadiin private
- PlayAudio(string name) dijadiin private

Item.cs:
- Tambahin AudioPlayerObj dan PlayAudio (sama kyk punya Interactable.cs), dibikin private juga
- Rename OnInteraction() jadi Pick() (pake ctrl+r+r, biarin aja error)
- Apus fungsi OnInteraction() yg barusan direname jadi Pick(), Pick() yg lama biarin aja
- Set Pick yg lama jadi public
- Apus interface IItem dan bikin interface baru (autogenerate aja)

Detectors:
- Pindahin semua fungsi dan variable di ObjectDetector.cs ke InteractableDetector.cs dan ItemDetector.cs terus sesuain tipenya (InteractableDetector buat Interactable aja, ItemDetector buat Item aja)
- Delete class ObjectDetector.cs
- Ilangin inheritance InteractableDetector.cs dan ItemDetector.cs ke ObjectDetector.cs
- GhostSimulationInteractableDetector.cs inherits ItemDetector.cs

How to check:
- Check the codes
- Run tests

### Tasks List
- [close #342 ]

2022-05-28 09:01 UTC, InShineStudios requested changes
Since Item is no longer a subclass of Interactable, the foldering should also change. Move the "Items" folder so that it is on the same level as the "Interactables" folder.

Adjust foldering as well for the Interactables and Items scripts:
Make folders by object name. For example folder named "Door" and inside are "DoorAnimator" and "DoorController" scripts. Similarly, do the same for all interactables (light switch, victim, closets). Also: rename "ClosetsController" to "ClosetController"

For items:
Make folder "ExorcismItem" and move the script to that folder. The other item scripts should be fine.

2022-05-31 07:18 UTC, rafiftaris requested changes
- Delete ObjectDetector.cs script

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/GhostSimulationInteractableDetector.cs
> +public class GhostSimulationInteractableDetector : ItemDetector
kalo sekarang fungsionalitasnya masih kasar (cuma dipake buat ngetes evidence item), kalo udah fix cara ghost interact dengan environment baru class ini bisa diexpand

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/InteractableDetector.cs
> +public class InteractableDetector : MonoBehaviour
betull

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/InteractableDetector.cs
> +    protected virtual void Awake()
not refered by any other class, set to private and remove virtual

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/InteractableDetector.cs
> +    protected virtual void InteractClosest(Interactable closest)
not refered by any other class, set to private and remove virtual

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/InteractableDetector.cs
> +    protected void UpdateClosestInteractable()
set to private

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/ItemDetector.cs
> +    protected virtual void Awake()
not refered by any other class, set to private and remove virtual

2022-05-31 07:18 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/ItemDetector.cs
> +    protected void UpdateClosestItem()
set to private

2022-05-31 10:08 UTC, VadimBhirawa commented on Assets/Astralization/Scripts/Player/Detectors/ItemDetector.cs
> +    protected virtual void Awake()
this one is refered by GhostSimulationInteractableDetector so I don't think it should be changed to private(?) (Error showed up after this was changed to private)

2022-05-31 13:28 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Detectors/ItemDetector.cs
> +    protected virtual void Awake()
oh okay lol, keep it that way then

2022-06-06 13:01 UTC, InShineStudios approved these changes
Nice refactoring

2022-06-06 15:15 UTC, rafiftaris approved these changes
mantapp bro!

2022-06-07 09:14 UTC, merged