[refactor] major refactoring
InShine-Studios/Horror-3D pull request #349
Opened 2022-06-08 11:34 UTC by rafiftaris

### Main changes
- Player UI Canvas Rework (HudManager and prefab structure)
- Deleted AudioManager.cs
- AstralMeterLogic.cs and StageManager.cs become singleton
- Player state to input map mapper (in PlayerHelper.cs)
- Eliminates most of `Find` method.

### Tasks List
- [close #329 ]
- [close #330 ]
- [close #331 ]
- [close #332 ]

### New Packages
- DependencyHunter (di folder Scripts/Editor)

2022-06-15 12:55 UTC, InShineStudios requested changes

2022-06-15 12:55 UTC, InShineStudios commented on Assets/Astralization/Scripts/Item/Item.cs
> +    private GameObject _model;
What is this model referring to? Is it a 3D marker for the item that is shown in the world?

2022-06-17 11:55 UTC, rafiftaris commented on Assets/Astralization/Scripts/Item/Item.cs
> +    private GameObject _model;
gameobject of the item model. for example: the gameobject that has the mesh of ankh

2022-06-23 12:57 UTC, uciii approved these changes
all is well

2022-06-24 12:38 UTC, merged