[Feature] Object Fading Between Camera and Player
InShine-Studios/Horror-3D pull request #359
Opened 2022-06-30 10:00 UTC by uciii

### Main changes
Create CameraDetector code to process all objects between camera and player. For usability tests, use FadeObjectTestScene in the Test folder.  

### Tasks List
- close #354 

### Attachments
We should assign a tag for objects that faded (FadeProperty). Video explanation: left shelf not in FadeProperty tag, a right shelf in FadeProperty tag.
https://user-images.githubusercontent.com/71260420/176648972-d3f75ba8-62e6-4fda-ab8d-1c3b457de919.mp4

Additional (bonus) shader graph
<img width="269" alt="image" src="https://user-images.githubusercontent.com/71260420/176649565-1aa778b8-b919-483b-a292-8517f68b3a92.png">

2022-07-03 12:27 UTC, rafiftaris requested changes
- put the `shadergraph` folder from `Developers/Uci` to `FX` folder
- use the exact type instead of `var` type to increase readability
- rename Transparant to Transparent

2022-07-03 12:27 UTC, rafiftaris commented on Assets/URP/ForwardRenderer.asset
> +    Event: 450
may i know what is the purpose of this modification?

2022-07-03 12:27 UTC, rafiftaris commented on Assets/Astralization/Scripts/Shaders/CameraDetector.cs
> +    [SerializeField] private Transform _player;
since `Camera` prefab and `Iris3D`prefab are siblings in `Player prefab, use `transform.find `instead

2022-07-03 12:27 UTC, rafiftaris commented on Assets/Astralization/Scripts/Shaders/CameraDetector.cs
> +        _camera = transform;
just access the transform directly without assigning it first to a variable

2022-07-04 06:13 UTC, JahnsMichael commented on Assets/URP/ForwardRenderer.asset
> +    Event: 450
ToonShading doesn't work correctly with material with transparent surface type because the render objects method only obtains color from the scene view, not from each material, so it cannot get the alpha value from objects. So, when the shader wants to create the cell-shaded effect, the scene color node doesn't detect the transparent-surface-type object, regardless of the alpha value in the material color. More on that in [the docs about Scene Color Node](https://docs.unity3d.com/Packages/com.unity.shadergraph@10.7/manual/Scene-Color-Node.html).

Actually, that was me that suggested this modification. Because it is easier to change the event for applying ToonShading than search for workarounds in the ToonShading shader graph. Visually, this method doesn't contain any differences except in the transparent object. ToonShading won't apply to the transparent object. But, we won't have many transparent objects, and it doesn't essential to have ToonShading applied to every object when fading near the camera.

2022-07-04 06:20 UTC, JahnsMichael commented on Assets/Astralization/Resources/3DMeshes/OutdoorDecorations/OutdoorPack/materials/props_0.mat
> +    - _Cutoff: 0.707
is this modification essential? because the OutdoorPack isn't used in the test scene.

2022-07-04 06:29 UTC, JahnsMichael reviewed
Good work! Finally, we have Fade Shader!!! But I have a question, is duplicating the material essential? And, if we change the alpha of the material that is used in other objects, will the alpha on the other objects change too?

2022-07-04 10:53 UTC, GustiNgurahYama commented
> Good work! Finally, we have Fade Shader!!! But I have a question, is duplicating the material essential? And, if we change the alpha of the material that is used in other objects, will the alpha on the other objects change too?

as discussed in discord, its work ya for duplicate object (with same material)

2022-07-04 11:01 UTC, JahnsMichael approved these changes
as my comment confirmed, then approved!

2022-07-04 12:19 UTC, rafiftaris approved these changes
clean & readable code and nice testing 👍

2022-07-05 09:36 UTC, merged