[feature] logo item animator
InShine-Studios/Horror-3D pull request #360
Opened 2022-07-01 15:14 UTC by rafiftaris

### Main changes

### Tasks List
- [close #347 ]
- [close #355 ]

### Attachments
- Ankh Logo Example
https://user-images.githubusercontent.com/51603162/176921885-5b51b212-b0ba-4820-9c4c-276d91db8c25.mp4

- Evidence Logo Example
https://user-images.githubusercontent.com/51603162/176921955-f7653eef-dab5-4b1e-9bc0-790ffab08c3a.mp4

2022-07-11 13:06 UTC, InShineStudios requested changes

2022-07-11 13:06 UTC, InShineStudios commented on Assets/Astralization/Scripts/Item/EvidenceItem/ClockItem.cs
> +        //_clockManager.ChangeState<ClockInactiveState>();
Why is this commented? If its not needed I think deleting it is fine

2022-07-11 13:06 UTC, InShineStudios commented on Assets/Astralization/Scripts/Item/EvidenceItem/SilhouetteBowlItem.cs
> +        //_silhouetteBowlManager.ChangeState<SilhouetteBowlInactiveState>();
Same for this line, delete if unnecessary

2022-07-11 13:06 UTC, InShineStudios commented on Assets/Astralization/Scripts/Item/EvidenceItem/ThermometerItem.cs
> +        //_thermometerManager.ChangeState<ThermometerInactiveState>();
Same as this line

2022-07-11 13:06 UTC, InShineStudios commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +// TODO: pindahin ke utils
Do we need to add this to backlog?

2022-07-11 15:26 UTC, rafiftaris commented on Assets/Astralization/Scripts/Item/EvidenceItem/ClockItem.cs
> +        //_clockManager.ChangeState<ClockInactiveState>();
Setting EvidenceItem to its negative state is **temporarily** disabled so the item logo can show active/positive/negative states when picked up. So is it better to just delete it?

2022-07-11 15:27 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +// TODO: pindahin ke utils
Sorry, I should have moved it since the ItemHelper.cs is already up to dev. Will fix later

2022-07-12 06:47 UTC, RaiRiz approved these changes
LGTM, fungsionalitas sudah jalan sesuai ekspektasi dan test juga semua success

2022-07-13 12:14 UTC, naufalhilmi12345 approved these changes
LGTM! cuman mau nanya buat evience item, sekali dipake itu gabisa di non-aktifin ya?? jadi akan selalu item setelah dipake pertama kali?? thanks

2022-07-13 13:11 UTC, rafiftaris commented on Assets/Astralization/Scripts/Item/EvidenceItem/ClockItem.cs
> +        //_clockManager.ChangeState<ClockInactiveState>();
tandain biar diuncomment

2022-07-14 11:57 UTC, merged