[feature] timeslot
InShine-Studios/Horror-3D pull request #385
Opened 2022-08-02 14:48 UTC by rafiftaris

### Main changes
- Implemented TimeslotStateMachine as a Timeslot manager
- Implemented dummy interactable that can advance time when interacted
- Implemented dummy hud and integrate it with TimeslotStateMachine

### Tasks List
- [close #375 ]

### Attachments

https://user-images.githubusercontent.com/51603162/182403702-4ccb222d-d7e7-45c0-9bc7-d5d1978fdbe4.mp4

2022-08-05 06:44 UTC, RaiRiz approved these changes

2022-08-07 08:37 UTC, VadimBhirawa approved these changes
The code looks good enough to me with the state machine, good job!

2022-08-07 14:45 UTC, RaiRiz approved these changes

2022-08-11 13:22 UTC, InShineStudios requested changes

2022-08-11 13:22 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs
> +    private int _timeJumpCount = 1;
Rename variable: _timeslotIncrement

2022-08-11 13:22 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/DummyTimeslotChanger/DummyTimeslotChanger.cs
> +    public static event Action<int> TimeJumpEvent;
Rename event: TimeslotIncrementEvent

2022-08-11 13:22 UTC, InShineStudios commented on Assets/Astralization/Scripts/Managers/GameManager.cs
> +    public void InvokeTimeJump(int jumpCount)
Rename function: InvokeTimeslotIncrement

2022-08-11 13:22 UTC, InShineStudios commented on Assets/Astralization/Scripts/Managers/HudManager.cs
> +    private void UpdateTimeDisplay(DateTimeslot dateTimeslot)
Rename function: UpdateTimeslotDisplay

2022-08-11 13:22 UTC, InShineStudios commented on Assets/Astralization/Scripts/States/TimeslotState/TimeslotStateMachine.cs
> +    public static event Action<DateTimeslot> UpdateTimeHudEvent;
Rename event: UpdateTimeslotHudEvent

2022-08-12 13:02 UTC, InShineStudios approved these changes

2022-08-12 13:02 UTC, merged