[rework] hiding camera
InShine-Studios/Horror-3D pull request #406
Opened 2022-08-30 13:35 UTC by naufalhilmi12345

### Main changes

- Rework camera when hiding

### Tasks List

- [ close #312 ]

### Attachments
can test this at naufal/hiding_test scene

https://user-images.githubusercontent.com/44135006/187450690-44d8d200-db18-484c-be8a-aa4665aed8b0.mp4

2022-09-01 16:25 UTC, rafiftaris requested changes
- enclose code within a region
- put docs above class
- public field use PascalCase
- move CinemachinePOVExtension to Scripts/Camera


In order to encapsulate the details of Closets from PlayerHidingState (PlayerHidingState only acts as a mediator to CinemachinePOVExtension), pass the whole ClosetCameraSettings directly to CinemachinePOVExtension and get the values in that class.

2022-09-11 00:01 UTC, rafiftaris requested changes
- remove on camera live event on the Camera Hiding gameobject. make sure to remove it on the prefab too
<img width="320" alt="image" src="https://user-images.githubusercontent.com/51603162/189505507-b6650b78-b164-4e4a-860b-543476224e6d.png">

2022-09-17 13:54 UTC, InShineStudios requested changes

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Closet/ClosetCameraSetting.cs
> +public class ClosetCameraSetting : MonoBehaviour
Rename class: Hiding Camera Configs

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Closet/ClosetCameraSetting.cs
> +    public Vector2 ClampAngleX;
Rename: Clamp Down Up

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Closet/ClosetCameraSetting.cs
> +    public Vector2 ClampAngleY;
Clamp Left Right

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Camera/CinemachinePOVExtension.cs
> +        _closetCameraSetting = closetCameraSetting;
Add Vector3 variable currentCameraDirection, save the original direction from Configs, use this variable to be adjusted on PostPipelineStageCallback

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Closet/ClosetCameraSetting.cs
> + * Class to keep value for camera
for hiding camera configs

2022-09-17 13:54 UTC, InShineStudios commented on Assets/Astralization/Scripts/Interactables/Closet/ClosetCameraSetting.cs
> +    #region Handler
Constructor

2022-09-22 12:22 UTC, rafiftaris commented
Reminder: Push test sama bikin diagram

2022-09-25 08:10 UTC, rafiftaris requested changes
the test is good but please rename this variable for clarity

2022-09-25 08:10 UTC, rafiftaris commented on Assets/Astralization/Tests/InteractableTest/InteractableTest.cs
> +        Vector3 startingPosition = hidingCameraConfigs.StartingPosition;
rename to hidingCameraStartingPosition

2022-09-25 13:04 UTC, rafiftaris approved these changes
looks great to me~

2022-09-25 13:06 UTC, InShineStudios approved these changes
Nicely done

2022-09-25 13:07 UTC, merged

2022-09-25 13:10 UTC, RaiRiz approved these changes