[rework] inventory hud
InShine-Studios/Horror-3D pull request #419
Opened 2022-10-11 03:46 UTC by naufalhilmi12345

### Main changes

- Rework inventory hud and its control

### Tasks List

- [ close #380 ]

### Attachments
can test this at naufal/invent_rework scene

https://user-images.githubusercontent.com/44135006/194992570-2db54846-aee7-4129-af6d-9fc44f6219f9.mp4

2022-10-15 11:56 UTC, rafiftaris requested changes

2022-10-15 11:56 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/Inventory.cs
> +    //[SerializeField]
delete this commented code

2022-10-15 11:56 UTC, rafiftaris commented on Assets/Input System/PlayerInputActions.inputactions
>                      "name": "ToggleItemHudDisplay",
remove this action, use the ChangeItem instead

2022-10-15 11:56 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/ItemHud/ItemHudDisplay.cs
>      public void ToggleDisplay()
remove this function, just call expand directly

2022-10-15 12:20 UTC, rafiftaris requested changes

2022-10-15 12:20 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerDefaultState.cs
> -            _inventory.SetActiveItemByQuickSlot(newIdx);
set quickslot related functions to obsolete instead of deleting it,  but remove every usage of that function. check these scripts and line numbers below:
- InputManager.cs (73)
- PlayerState.cs (38)
- Inventory.cs (16)

reference: https://answers.unity.com/questions/559529/how-to-mark-a-method-obsolete.html
set the **error flag to false**

2022-10-19 13:51 UTC, rafiftaris requested changes

2022-10-22 23:17 UTC, rafiftaris requested changes
functionality and test works well

2022-10-22 23:17 UTC, rafiftaris approved these changes
functionality and test works well

2022-10-24 07:29 UTC, RaiRiz approved these changes

2022-10-28 13:15 UTC, merged