Rafif/feature/mind map camera navigation
InShine-Studios/Horror-3D pull request #423
Opened 2022-11-10 13:49 UTC by rafiftaris

### Main changes
```
Clearly and concisely describe the feature(s) that you developed.
```

### Tasks List
```
Link your Card to the PR by adding description: KEYWORD #CARD-NUMBER >
- close - For issues regarding creating new feature
- fix - For issues regarding bug fixes
- resolve - For issues regarding merge conflicts

Example : [close #10]
```

### Attachments
```
Screenshot(s) / short video(s) about the feature(s) result that you developed.
```

### New Packages
```
List of new packages that you use to developed the feature(s)
```

### Resources 
```
List of url(s) used to developed the feature(s)
```

2023-01-08 09:28 UTC, naufalhilmi12345 approved these changes
LGTM!

2023-01-08 09:31 UTC, worthlessowl commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerState.cs
> +        Utils.LoggerHelper.PrintStateDefaultLog("Player", "ChangeCore");
Ini emang mau di log kayak gini kah? apakah ntar akan dihapus?

2023-01-08 09:31 UTC, worthlessowl commented on Assets/Astralization/Scripts/Player/PlayerStates/UiManager.cs
> +
ini methods disini emang sengaja dibuat kososng ya?

2023-01-08 09:31 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/ChapterNavigation.cs
> +
Yang ini juga emang sengaja kosong ya?

2023-01-08 09:32 UTC, worthlessowl approved these changes

2023-01-08 13:56 UTC, InShineStudios requested changes

2023-01-08 13:56 UTC, InShineStudios commented on Assets/Astralization/Scripts/Camera/CameraConstants.cs
> +using System.Collections;
Move to folder Utils?

2023-01-08 13:56 UTC, InShineStudios commented on Assets/Astralization/Scripts/Camera/CameraConstants.cs
> +public class CameraConstants : MonoBehaviour
Class name should be CameraHelper (standardize from Utils)

2023-01-08 13:56 UTC, InShineStudios commented on Assets/CameraManager.cs
> +using Cinemachine;
Is this script correctly placed? Its not in Scripts folder?

2023-01-08 13:56 UTC, InShineStudios commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerCluesMindMapState.cs
> +public class PlayerCluesMindMapState : PlayerState
Since accessing the Mind Map will be through the In Game Pause menu first, will this state be separated from the other Pause State or not? Because it might be redundant to split every pause menu to a different player state?

2023-01-09 11:42 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerState.cs
> +        Utils.LoggerHelper.PrintStateDefaultLog("Player", "ChangeCore");
iyaa, PlayerState itu base class dari semua PlayerState subclasses lain. By default bakal munculin log semacam "Not implemented in this State", dan subclasses cuma perlu override methods yang terkait sama konteks dari subclass itu aja

2023-01-09 11:43 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/UiManager.cs
> +
class ini niatnya masih TODO, bakal diimplementasi pas mau implementasi menu2 lain

2023-01-09 11:44 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/ChapterNavigation.cs
> +
iyaa, yang ini bisa dipake buat task kita #431 nanti

2023-01-09 12:17 UTC, rafiftaris commented on Assets/Astralization/Scripts/Player/PlayerStates/PlayerCluesMindMapState.cs
> +public class PlayerCluesMindMapState : PlayerState
I agree, I will take note to implement all pause menu related controls to this class

2023-01-10 12:22 UTC, InShineStudios approved these changes
Good job!

2023-01-13 10:39 UTC, worthlessowl approved these changes

2023-01-15 12:36 UTC, merged