Agung/feature/store camera value on mindmaptree
InShine-Studios/Horror-3D pull request #432
Opened 2022-12-25 12:20 UTC by worthlessowl

### Main changes
```
Serialize CameraLookAt and CameraFollow object position for Mind Map. This PR implements the code related to saving and loading serialized value of CameraLookAt and CameraFollow
```

### Tasks List
```
close #430 
```

### Attachments
```
Screenshot(s) / short video(s) about the feature(s) result that you developed.
```

### New Packages
```
List of new packages that you use to developed the feature(s)
-
```

### Resources 
```
List of url(s) used to developed the feature(s)
```

2023-01-01 15:57 UTC, rafiftaris requested changes
Note: Thank you very much! I just learned another useful tag `[ExecuteInEditMode]` for that is very suitable for developing builders.

2023-01-01 15:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +    private Vector3 _cameraStartingPosition;
we dont use this field, remove this field together with its decorator

2023-01-01 15:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +    private Vector3 _cameraStartingAngle;
we dont use this field, remove this field together with its decorator

2023-01-01 15:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapBuilder.cs
> +            mindMapTreeData.NodeCameraFollowPosition.Add(currentNode.GetCameraFollow().localPosition) ;
remove whitespace before ;

2023-01-01 15:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +[ExecuteInEditMode]
MindMapNode is actually intended for runtime, not limited on builder purpose so I think this tag will make the editor heavier in the future. Use null checker on SetGet instead. When the field is null, use transform get first.

2023-01-01 15:57 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapTree.cs
> +[ExecuteInEditMode]
similar to the MindMapNode tag, use null checker on SetGet instead.

2023-01-07 03:59 UTC, naufalhilmi12345 approved these changes
LGTM for implementation. for code agree with rafif.

2023-01-08 07:38 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +    private Vector3 _cameraStartingPosition;
Addressed on 432d630c9c1a56d51d7092dba3376b7fbdda5392

2023-01-08 07:38 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +    private Vector3 _cameraStartingAngle;
432d630c9c1a56d51d7092dba3376b7fbdda5392

2023-01-08 07:38 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/MindMapBuilder.cs
> +            mindMapTreeData.NodeCameraFollowPosition.Add(currentNode.GetCameraFollow().localPosition) ;
addressed on 6322f656a4330b1ddb922f3167f00579ace10be0

2023-01-08 07:38 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/MindMapNode.cs
> +[ExecuteInEditMode]
Addressed on 432d630c9c1a56d51d7092dba3376b7fbdda5392

2023-01-08 07:38 UTC, worthlessowl commented on Assets/Astralization/Scripts/UI/MindMap/MindMapTree.cs
> +[ExecuteInEditMode]
Addressed on 432d630c9c1a56d51d7092dba3376b7fbdda5392

2023-01-09 11:59 UTC, rafiftaris requested changes
the camera fields of the builder works perfectly but dont forget to update [this docs](https://docs.google.com/document/d/1jOUZTEIYtaI7TXRxwd3nMmKrF3J6jxNX5DeyHS1iMV4/edit?usp=sharing). I'll approve immediately after the docs and this requested change are resolved

2023-01-09 11:59 UTC, rafiftaris commented on Assets/Astralization/UI/ChapterClues/MindMapNode.prefab
> +  m_LocalPosition: {x: 0, y: -5, z: 0}
change the y value to 0. change this transform of `CameraFollow` gameobject by opening the `MindMapNode` prefab

2023-01-19 14:17 UTC, rafiftaris requested changes

2023-01-19 14:17 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapTree.cs
> +            // Type-related assignments
duplicated after merging

2023-01-19 14:35 UTC, rafiftaris approved these changes
LGTM!

2023-01-20 12:50 UTC, merged