[feature] Chapter clues tooltip
InShine-Studios/Horror-3D pull request #441
Opened 2023-02-01 14:56 UTC by naufalhilmi12345

### Main changes

- Adding implementation chapter clues tooltip

### Tasks List

- [close #403]

### Attachments

https://user-images.githubusercontent.com/44135006/216077471-312bf0c3-8180-4db7-b4d3-eb96ca402737.mp4

2023-02-08 12:55 UTC, rafiftaris requested changes

2023-02-08 12:55 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapTree.cs
> +        SendNodeInfo(Root.Children[coreNodeIdx]);
when opening the mind map, immediately show tooltip on chapter node

2023-02-08 13:53 UTC, rafiftaris requested changes

2023-02-08 13:53 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapModal.cs
> +    }
listener for HUD events should be put on `HudManager` instead of inside the HUD component directly

2023-02-08 13:53 UTC, rafiftaris commented on Assets/Astralization/Scripts/UI/MindMap/MindMapModal.cs
> +    }
dont forget to update the diagram too

2023-02-08 13:53 UTC, rafiftaris commented on Assets/Astralization/Scripts/Camera/MindMapCameraManager.cs
> +        return _cinemachineBrain;
instead of returning the whole `CinemachineBrain` instance, just return the `m_DefaultBlend.m_Time`

2023-02-10 10:32 UTC, naufalhilmi12345 commented on Assets/Astralization/Scripts/UI/MindMap/MindMapTree.cs
> +        SendNodeInfo(Root.Children[coreNodeIdx]);
I still don't get it about this review situation. can you elaborate more this review?

2023-02-12 01:32 UTC, rafiftaris requested changes

2023-02-12 01:32 UTC, rafiftaris commented on Assets/Astralization/Scripts/Managers/HudManager.cs
> +        _mindMapModal = GameObject.Find("MindMapCanvas").GetComponentInChildren<MindMapModal>();
dont use `GameObject.Find`, use `transform.parent.GetComponentInChildren` instead

2023-02-12 11:09 UTC, worthlessowl approved these changes

2023-02-12 12:59 UTC, InShineStudios approved these changes

2023-02-12 13:00 UTC, rafiftaris approved these changes
LGTM!

2023-02-12 13:04 UTC, merged