[feature] migrate player sprint
InShine-Studios/Horror-3D pull request #47
Opened 2022-01-02 15:21 UTC by naufalhilmi12345

### Main changes
- Adding logic player to sprint.
- Changing logic movement player
### Tasks List
- [close #22 ]

### Attachments

https://user-images.githubusercontent.com/44135006/147876660-d5f96337-5736-46d1-92ed-e62bc4f8eca2.mp4

2022-01-03 13:51 UTC, rafiftaris requested changes
will be approved after requested changes is fulfilled and also you have streamed Kep1er - WA DA DA

2022-01-03 13:51 UTC, rafiftaris commented on Assets/Dev/Scripts/Player/PlayerMovement.cs
> +            isSprinting = true;
use curly brackets because there's 2 line inside if condition (including Debug)

2022-01-03 13:51 UTC, rafiftaris commented on Assets/Dev/Scripts/Player/PlayerMovement.cs
> +            isSprinting = false;
use curly brackets because there's 2 line inside if condition (including Debug)

2022-01-03 13:51 UTC, rafiftaris commented on Assets/Dev/Scripts/Player/PlayerMovement.cs
> +        if (inputVal.performed)
delete this condition, this caused nonstop movement

2022-01-04 09:11 UTC, RaiRiz approved these changes

2022-01-04 11:57 UTC, rafiftaris requested changes
LGTM!

Note:
- Drafted new bug "Player doesn't sprint properly when walking down stairs" to board
- Mentioned @naufalhilmi12345 in feature docs regarding sprint controls

Sorry wrong comment type lol 😅

2022-01-04 11:59 UTC, rafiftaris approved these changes

2022-01-04 13:29 UTC, merged