[feature][refactor] Migrate inventory, item. Refactor interact input action.
InShine-Studios/Horror-3D pull request #50
Opened 2022-01-05 16:29 UTC by rafiftaris

### Main changes
- Set interact input action to player events
- Split dark scene into interactable tester and item tester
- Migrated inventory and item class
- Implemented dummy item flashlight for testing

### Tasks List
- [close #33 ]
- [close #34 ]
- [close #35 ]
- [close #36 ]

### Attachments

https://user-images.githubusercontent.com/51603162/148253127-1d6aece7-e80c-48ad-aada-5e941832afbf.mp4

2022-01-06 09:22 UTC, naufalhilmi12345 approved these changes
LGTM!!

2022-01-06 15:57 UTC, raihansyahdean requested changes
Minor Clean Code

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs
> +    private void Awake()
Change to Start() and also change the InteractableDetector as well. Move the GetComponent to the Start() too.

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Detectors/ItemDetector.cs
> +    public Inventory inventory;
Change to private and add GetComponent in Start()

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Utils/MathCalcu.cs
> +}
Add new line

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Inventory.cs
> +    private Vector3 activeItemYOffset = new Vector3(0, -0.5f, 0);
Change to public and edit it through the inspector

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Inventory.cs
> +                activeItem.gameObject.transform.parent = GameObject.Find("OverworldItems").transform;
make OverworldItems a public var and assign through inspector

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Inventory.cs
> +                numOfItem++;
Add TODO: Update Inventory HUD

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Inventory.cs
> +        }
Add TODO: Change Active Item HUD

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Player/Inventory.cs
> +                activeItem.SetCollider(true);
move to below SetMeshRenderer

2022-01-06 15:57 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Item/Item.cs
> +        SetMeshRenderer(false);
Move to Pick()

2022-01-07 10:22 UTC, rafiftaris commented on Assets/Dev/Scripts/Player/Inventory.cs
> +        }
this function is UseActiveItem, already added in ChangeActiveItem function

2022-01-08 12:21 UTC, raihansyahdean approved these changes
Nicely done!

2022-01-09 08:52 UTC, merged