Naufal/feature/3d icon
InShine-Studios/Horror-3D pull request #81
Opened 2022-01-14 02:59 UTC by naufalhilmi12345

### Main changes

- Adding 3D icon to guide light switch
- Changing audio for light switch using AudioManager prefab

### Tasks List

- [close #61]
- [close #62]

### Attachments

- For 3D Icon

https://user-images.githubusercontent.com/44135006/149443928-0ee34473-8f11-4227-87d4-ebbf1512cd70.mp4

- For AudioManager
![messageImage_1642128978001](https://user-images.githubusercontent.com/44135006/149443960-0e96272d-ab1f-48c7-a332-bf4aae1b8ab8.jpg)

2022-01-14 17:47 UTC, rafiftaris requested changes
- Change prefab name to 3d-Exclamation-Mark since it's not question mark 😆 
- Maybe put guiding icon to a directory for guiding icon themselves
- Can Audio Manager show detailed configuration options for Audio Source like when Audio Source become an component itself. Graph distance adjustment and other things may be needed to be customized

2022-01-15 17:07 UTC, ahmadhaydar approved these changes
:poggers:

2022-01-16 05:22 UTC, raihansyahdean requested changes
Add audio functionality (if-else) in:
- LightSwitchController
- DummyFlashlight

Add AudioManager in DummyFlashlight prefab

2022-01-16 05:22 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Interactable.cs
>          if (isOn)
rename boolean to state

2022-01-16 05:22 UTC, raihansyahdean commented on Assets/Dev/Scripts/Interactables/Interactable.cs
> +            audioManager.Play("Switch_On");
change functionality to only audioManager.Play("name")

2022-01-16 08:41 UTC, rafiftaris approved these changes

2022-01-16 09:07 UTC, raihansyahdean approved these changes

2022-01-16 09:07 UTC, merged